/**
 * WordPress, connected and then written to.
 *
 * The good surprise in this whole area: WordPress has shipped an authorisation
 * screen since 5.6. Send the user to
 * `/wp-admin/authorize-application.php?app_name=…&success_url=…`, they press
 * Approve inside their own admin, and WordPress posts back the site URL, the
 * username and a freshly minted application password. No plugin, no OAuth
 * registration, no pasting a secret out of a settings screen. It behaves like
 * OAuth and it works on any self-hosted install over https.
 *
 * What it cannot do is as important as what it can. Core WordPress has no
 * meta description field, so one is written through Yoast's or Rank Math's
 * post meta when either is installed, and reported as unsupported when
 * neither is. robots.txt is generated by WordPress at request time and is not
 * a file the REST API can replace. Saying so is better than a green tick over
 * a change that never landed.
 */

import { basicAuth, type ConnectionRow } from "./connections";
import type { Env } from "./env";
import { validateUrl } from "./safe-fetch";

import { BRAND } from "@/lib/brand";

export type WpIdentity = { siteUrl: string; user: string; password: string };

/** The URL that asks a WordPress admin to approve this app. */
export function authorizeUrl(siteUrl: string, successUrl: string, appId: string): string {
  const base = new URL(siteUrl);
  const url = new URL("/wp-admin/authorize-application.php", base);
  url.searchParams.set("app_name", BRAND);
  url.searchParams.set("app_id", appId);
  url.searchParams.set("success_url", successUrl);
  return url.toString();
}

export type Capabilities = {
  restReachable: boolean;
  canEditPosts: boolean;
  seoPlugin: "yoast" | "rankmath" | null;
  user: string | null;
  error: string | null;
};

/** What this install will actually let us do, asked rather than assumed. */
export async function capabilities(e: Env, row: ConnectionRow, siteUrl: string): Promise<Capabilities> {
  const out: Capabilities = { restReachable: false, canEditPosts: false, seoPlugin: null, user: null, error: null };
  try {
    const auth = await basicAuth(e, row);
    const me = await fetch(new URL("/wp-json/wp/v2/users/me?context=edit", siteUrl).toString(), {
      headers: { authorization: auth },
    });
    if (!me.ok) {
      out.error = `WordPress answered ${me.status} when asked who we are signed in as.`;
      return out;
    }
    out.restReachable = true;
    const body = (await me.json()) as { slug?: string; capabilities?: Record<string, boolean> };
    out.user = body.slug ?? null;
    out.canEditPosts = Boolean(body.capabilities?.edit_posts ?? body.capabilities?.administrator);

    const root = await fetch(new URL("/wp-json/", siteUrl).toString(), { headers: { authorization: auth } });
    if (root.ok) {
      const text = await root.text();
      if (text.includes("yoast")) out.seoPlugin = "yoast";
      else if (text.includes("rank-math") || text.includes("rankmath")) out.seoPlugin = "rankmath";
    }
  } catch (error) {
    out.error = error instanceof Error ? error.message : String(error);
  }
  return out;
}

export type Resolved = { postId: number; postType: "posts" | "pages"; link: string; title: string };

/**
 * Turn a URL from the crawl into something the REST API can write to.
 *
 * The audit knows URLs. WordPress writes by id. The bridge is the slug, which
 * is the last path segment, checked against pages first and then posts because
 * the things this product most often rewrites, titles and meta descriptions on
 * commercial pages, are usually pages.
 *
 * A URL that resolves to nothing is reported as such rather than guessed at. A
 * publish that writes to the wrong post is worse than one that does not run.
 */
export async function resolveUrl(
  e: Env,
  row: ConnectionRow,
  siteUrl: string,
  pageUrl: string,
): Promise<Resolved | null> {
  let slug = "";
  try {
    const parts = new URL(pageUrl).pathname.split("/").filter(Boolean);
    slug = parts[parts.length - 1] ?? "";
  } catch {
    return null;
  }
  // The front page has no slug. WordPress exposes it as the page whose id is
  // in the site settings, which an application password can read.
  if (!slug) {
    try {
      const settings = await wpRequest(e, row, siteUrl, "/wp-json/wp/v2/settings");
      const front = Number(settings.page_on_front ?? 0);
      if (!front) return null;
      const page = await wpRequest(e, row, siteUrl, `/wp-json/wp/v2/pages/${front}?context=edit`);
      return { postId: front, postType: "pages", link: String(page.link ?? pageUrl), title: rendered(page.title) ?? "" };
    } catch {
      return null;
    }
  }

  for (const postType of ["pages", "posts"] as const) {
    try {
      const auth = await basicAuth(e, row);
      const response = await fetch(
        new URL(`/wp-json/wp/v2/${postType}?slug=${encodeURIComponent(slug)}&context=edit&per_page=2`, siteUrl).toString(),
        { headers: { authorization: auth } },
      );
      if (!response.ok) continue;
      const found = (await response.json()) as Record<string, unknown>[];
      if (found.length === 1) {
        const hit = found[0];
        return {
          postId: Number(hit.id),
          postType,
          link: String(hit.link ?? pageUrl),
          title: rendered(hit.title) ?? "",
        };
      }
      // Two things sharing a slug across types is ambiguous, and ambiguity is
      // exactly when a tool should stop rather than pick.
      if (found.length > 1) return null;
    } catch {
      // Try the next type.
    }
  }
  return null;
}

export type PublishAction =
  | { kind: "post_title"; postId: number; postType?: string; value: string }
  | { kind: "post_excerpt"; postId: number; postType?: string; value: string }
  | { kind: "meta_description"; postId: number; postType?: string; value: string }
  | { kind: "image_alt"; mediaId: number; value: string };

/**
 * What the browser sends: a URL and a field, because that is what the audit
 * knows. Turned into a PublishAction by `planFor` once the URL resolves.
 */
export type PublishRequest = { kind: "post_title" | "post_excerpt" | "meta_description"; url: string; value: string };

export type Plan = { action: PublishAction; target: Resolved } | { action: null; reason: string };

/** Resolve a request against the live site, or say why it cannot be resolved. */
export async function planFor(e: Env, row: ConnectionRow, siteUrl: string, request: PublishRequest): Promise<Plan> {
  const target = await resolveUrl(e, row, siteUrl, request.url);
  if (!target) {
    return {
      action: null,
      reason:
        `No single WordPress page or post matches ${request.url}. It may be an archive, a taxonomy page or ` +
        "generated by a theme, none of which the REST API can rewrite. The text is on the approval to paste in.",
    };
  }
  return {
    action: { kind: request.kind, postId: target.postId, postType: target.postType, value: request.value },
    target,
  };
}

export type PublishResult = {
  ok: boolean;
  /** The value that was there before, so the change can be reversed. */
  before: string | null;
  after: string | null;
  message: string;
};

async function wpRequest(
  e: Env,
  row: ConnectionRow,
  siteUrl: string,
  path: string,
  init?: RequestInit,
): Promise<Record<string, unknown>> {
  const auth = await basicAuth(e, row);
  const response = await fetch(new URL(path, siteUrl).toString(), {
    ...init,
    headers: { authorization: auth, "content-type": "application/json", ...(init?.headers ?? {}) },
  });
  const text = await response.text();
  if (!response.ok) {
    let detail = text.slice(0, 300);
    try {
      const parsed = JSON.parse(text) as { message?: string };
      if (parsed.message) detail = parsed.message;
    } catch {
      // Keep the raw body.
    }
    throw new Error(`WordPress answered ${response.status}: ${detail}`);
  }
  return JSON.parse(text) as Record<string, unknown>;
}

function rendered(value: unknown): string | null {
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && "raw" in value) return String((value as { raw: unknown }).raw ?? "");
  if (value && typeof value === "object" && "rendered" in value) return String((value as { rendered: unknown }).rendered ?? "");
  return null;
}

/**
 * Apply one approved change to a live WordPress site.
 *
 * Reads the current value first, writes, then reports both. The pair is what
 * `publishes` stores, and it is what makes "undo" a route rather than a
 * support ticket.
 */
export async function publish(
  e: Env,
  row: ConnectionRow,
  siteUrl: string,
  action: PublishAction,
  seoPlugin: "yoast" | "rankmath" | null,
): Promise<PublishResult> {
  if (action.kind === "image_alt") {
    const current = await wpRequest(e, row, siteUrl, `/wp-json/wp/v2/media/${action.mediaId}?context=edit`);
    const before = typeof current.alt_text === "string" ? current.alt_text : null;
    await wpRequest(e, row, siteUrl, `/wp-json/wp/v2/media/${action.mediaId}`, {
      method: "POST",
      body: JSON.stringify({ alt_text: action.value }),
    });
    return { ok: true, before, after: action.value, message: "Alt text updated." };
  }

  const type = action.postType ?? "posts";
  const path = `/wp-json/wp/v2/${type}/${action.postId}`;
  const current = await wpRequest(e, row, siteUrl, `${path}?context=edit`);

  if (action.kind === "post_title") {
    const before = rendered(current.title);
    await wpRequest(e, row, siteUrl, path, { method: "POST", body: JSON.stringify({ title: action.value }) });
    return { ok: true, before, after: action.value, message: "Title updated." };
  }

  if (action.kind === "post_excerpt") {
    const before = rendered(current.excerpt);
    await wpRequest(e, row, siteUrl, path, { method: "POST", body: JSON.stringify({ excerpt: action.value }) });
    return { ok: true, before, after: action.value, message: "Excerpt updated." };
  }

  // meta_description. Core WordPress has no such field; these are the two
  // plugins that between them cover most of the installed base.
  const key = seoPlugin === "yoast" ? "_yoast_wpseo_metadesc" : seoPlugin === "rankmath" ? "rank_math_description" : null;
  if (!key) {
    return {
      ok: false,
      before: null,
      after: null,
      message:
        "This site has neither Yoast nor Rank Math, and WordPress itself has no meta description field. " +
        "Install either one and this change becomes publishable, or paste the text into whatever SEO plugin is in use.",
    };
  }
  const meta = (current.meta ?? {}) as Record<string, unknown>;
  const before = typeof meta[key] === "string" ? (meta[key] as string) : null;
  try {
    await wpRequest(e, row, siteUrl, path, { method: "POST", body: JSON.stringify({ meta: { [key]: action.value } }) });
  } catch (error) {
    return {
      ok: false,
      before,
      after: null,
      message:
        `${error instanceof Error ? error.message : String(error)}. ` +
        "Some versions of these plugins do not expose their meta fields to the REST API, in which case this one has to be pasted in by hand.",
    };
  }
  return { ok: true, before, after: action.value, message: "Meta description updated." };
}

/** Reverse a publish by writing the previous value back. */
export async function revert(
  e: Env,
  row: ConnectionRow,
  siteUrl: string,
  action: PublishAction,
  before: string | null,
  seoPlugin: "yoast" | "rankmath" | null,
): Promise<PublishResult> {
  return publish(e, row, siteUrl, { ...action, value: before ?? "" } as PublishAction, seoPlugin);
}

/** The site is a real, reachable, public https origin before anything is sent. */
export async function checkSiteUrl(raw: string): Promise<string> {
  const url = await validateUrl(raw);
  if (url.protocol !== "https:") {
    throw new Error("A WordPress connection has to be over https: the application password travels with every request.");
  }
  return url.origin;
}
