/**
 * The check catalogue.
 *
 * Severity, impact, effort, confidence and the recommendation live in one
 * table rather than inside the check functions, so the same issue scores
 * identically wherever it is found and a client can be shown the whole
 * methodology. This mirrors packages/seoos/analysis/findings.py; the two are
 * kept in step deliberately, because the server engine and the browser engine
 * must not disagree about what "critical" means.
 */

import type { Category, Severity } from "./types";

export type CheckDef = {
  code: string;
  category: Category;
  severity: Severity;
  title: string;
  why: string;
  recommendation: string;
  impact: number;
  effort: number;
  confidence: number;
  autoFixable: boolean;
  fixStrategy: string | null;
};

function c(
  code: string,
  category: Category,
  severity: Severity,
  title: string,
  why: string,
  recommendation: string,
  opts: Partial<Pick<CheckDef, "impact" | "effort" | "confidence" | "autoFixable" | "fixStrategy">> = {},
): CheckDef {
  return {
    code,
    category,
    severity,
    title,
    why,
    recommendation,
    impact: opts.impact ?? 0.5,
    effort: opts.effort ?? 0.4,
    confidence: opts.confidence ?? 0.8,
    autoFixable: opts.autoFixable ?? false,
    fixStrategy: opts.fixStrategy ?? null,
  };
}

const DEFS: CheckDef[] = [
  /* -- indexability and crawl -------------------------------------------- */
  c("page_noindex", "technical", "critical",
    "Page is blocked from indexing",
    "A noindex directive removes the page from search results entirely.",
    "Remove the noindex meta tag or X-Robots-Tag header if this page should rank.",
    { impact: 1.0, effort: 0.2, confidence: 0.95 }),
  c("page_5xx", "technical", "critical",
    "Server error",
    "A 5xx page cannot be indexed and burns crawl budget on every visit.",
    "Fix the server error. If the page is retired, return 410 or redirect it.",
    { impact: 1.0, effort: 0.6 }),
  c("page_404_linked", "technical", "high",
    "Broken internal link",
    "Internal links to 404s waste crawl budget and strand users mid-journey.",
    "Repoint the link to the live URL or remove it.",
    { impact: 0.6, effort: 0.2, autoFixable: true, fixStrategy: "repoint_internal_link" }),
  c("redirect_chain", "technical", "medium",
    "Redirect chain",
    "Each extra hop loses a little authority and adds latency.",
    "Point the first URL straight at the final destination.",
    { impact: 0.4, effort: 0.3, autoFixable: true, fixStrategy: "flatten_redirect" }),
  c("redirect_loop", "technical", "critical",
    "Redirect loop",
    "The URL never resolves, so neither users nor crawlers reach content.",
    "Break the loop and point the chain at a single final URL.",
    { impact: 1.0, effort: 0.4 }),
  c("robots_blocks_important", "technical", "critical",
    "robots.txt blocks a page that should rank",
    "Disallowed URLs cannot be crawled, so their content never enters the index.",
    "Narrow the Disallow rule so it no longer covers this path.",
    { impact: 1.0, effort: 0.2 }),
  c("robots_missing", "technical", "low",
    "No robots.txt",
    "Without one, every crawler guesses, and you lose the place to declare your sitemap.",
    "Publish a robots.txt that allows what should be crawled and names the sitemap.",
    { impact: 0.25, effort: 0.1, autoFixable: true, fixStrategy: "generate_robots" }),
  c("orphan_page", "technical", "medium",
    "Orphan page",
    "No internal link points here, so it gets little crawl attention and no internal authority.",
    "Link to it from a relevant hub or category page.",
    { impact: 0.5, effort: 0.3, autoFixable: true, fixStrategy: "add_internal_link" }),
  c("deep_page", "technical", "low",
    "Page is more than four clicks from the homepage",
    "Depth correlates with crawl frequency and with how much internal authority a page receives.",
    "Add a link from a shallower hub page.",
    { impact: 0.3, effort: 0.3, autoFixable: true, fixStrategy: "add_internal_link" }),
  c("no_sitemap", "technical", "high",
    "No XML sitemap found",
    "A sitemap is how a search engine learns about pages your internal links miss.",
    "Publish an XML sitemap and reference it from robots.txt.",
    { impact: 0.6, effort: 0.3, autoFixable: true, fixStrategy: "generate_sitemap" }),
  c("sitemap_contains_non_indexable", "technical", "medium",
    "Sitemap lists pages that cannot be indexed",
    "Submitting noindex or redirected URLs sends a contradictory signal.",
    "Remove non-indexable URLs from the sitemap.",
    { impact: 0.4, effort: 0.2, autoFixable: true, fixStrategy: "clean_sitemap" }),
  c("sitemap_missing_pages", "technical", "medium",
    "Sitemap omits pages that are live and indexable",
    "Pages missing from the sitemap rely entirely on internal links to be found.",
    "Regenerate the sitemap from the live, indexable URL set.",
    { impact: 0.35, effort: 0.2, autoFixable: true, fixStrategy: "generate_sitemap" }),
  c("no_https", "technical", "critical",
    "Page is not served over HTTPS",
    "HTTPS is a ranking signal and browsers warn users on insecure pages.",
    "Install a certificate and redirect all HTTP traffic to HTTPS.",
    { impact: 0.9, effort: 0.5 }),
  c("mixed_content", "technical", "high",
    "HTTPS page loads insecure resources",
    "Browsers block or warn on mixed content, breaking the page for some users.",
    "Serve every subresource over HTTPS.",
    { impact: 0.5, effort: 0.3 }),
  c("no_lang_attribute", "technical", "low",
    "No lang attribute on the html element",
    "Screen readers and translation systems need to know the document language.",
    "Set lang on the html element to the page's actual language.",
    { impact: 0.2, effort: 0.1, autoFixable: true, fixStrategy: "set_lang" }),

  /* -- canonical and duplication ----------------------------------------- */
  c("canonical_missing", "technical", "medium",
    "No canonical tag",
    "Without a canonical, parameter and variant URLs compete with each other.",
    "Add a self-referencing canonical to every indexable page.",
    { impact: 0.4, effort: 0.2, autoFixable: true, fixStrategy: "add_self_canonical" }),
  c("canonical_mismatch", "technical", "high",
    "Canonical points to a different page",
    "The page is telling search engines to index something else, so it will not rank.",
    "Point the canonical at this URL unless it really is a duplicate.",
    { impact: 0.7, effort: 0.2 }),
  c("duplicate_content", "content", "high",
    "Duplicate page content",
    "Identical content splits signals between URLs and can suppress all of them.",
    "Consolidate to one URL and redirect or canonicalise the rest.",
    { impact: 0.6, effort: 0.5 }),
  c("duplicate_title", "content", "medium",
    "Duplicate title tag",
    "Identical titles make pages compete and give searchers no reason to pick one.",
    "Write a distinct title reflecting each page's specific topic.",
    { impact: 0.4, effort: 0.2, autoFixable: true, fixStrategy: "rewrite_title" }),
  c("duplicate_meta_description", "content", "low",
    "Duplicate meta description",
    "Repeated descriptions lower click-through because the snippet is not about this page.",
    "Write a distinct description for each page.",
    { impact: 0.25, effort: 0.2, autoFixable: true, fixStrategy: "rewrite_meta" }),

  /* -- on-page ------------------------------------------------------------ */
  c("title_missing", "content", "high",
    "Missing title tag",
    "The title is the strongest on-page relevance signal and the search result headline.",
    "Write a title of 50 to 60 characters that leads with the page's primary topic.",
    { impact: 0.8, effort: 0.1, autoFixable: true, fixStrategy: "rewrite_title" }),
  c("title_too_long", "content", "low",
    "Title is longer than the search snippet",
    "Truncated titles hide the part that would have earned the click.",
    "Trim to roughly 60 characters, keeping the distinguishing words first.",
    { impact: 0.25, effort: 0.1, autoFixable: true, fixStrategy: "rewrite_title" }),
  c("title_too_short", "content", "low",
    "Title is very short",
    "A short title leaves relevance and click-through on the table.",
    "Expand it to describe what the page actually answers.",
    { impact: 0.25, effort: 0.1, autoFixable: true, fixStrategy: "rewrite_title" }),
  c("meta_description_missing", "content", "medium",
    "Missing meta description",
    "Search engines will assemble a snippet themselves, usually less persuasively.",
    "Write 140 to 160 characters that state the benefit and invite the click.",
    { impact: 0.35, effort: 0.1, autoFixable: true, fixStrategy: "rewrite_meta" }),
  c("meta_description_length", "content", "low",
    "Meta description is outside the snippet length",
    "Too short wastes the space; too long gets cut mid-sentence.",
    "Aim for 140 to 160 characters.",
    { impact: 0.2, effort: 0.1, autoFixable: true, fixStrategy: "rewrite_meta" }),
  c("h1_missing", "content", "medium",
    "No H1 heading",
    "The H1 confirms the page topic to readers, assistive technology and crawlers.",
    "Add one H1 that matches the page's primary topic.",
    { impact: 0.4, effort: 0.1, autoFixable: true, fixStrategy: "add_h1" }),
  c("h1_multiple", "content", "low",
    "More than one H1",
    "Multiple H1s blur which topic the page is actually about.",
    "Keep one H1 and demote the others to H2.",
    { impact: 0.2, effort: 0.2, autoFixable: true, fixStrategy: "fix_heading_hierarchy" }),
  c("heading_hierarchy_broken", "content", "low",
    "Heading levels skip",
    "Jumping from H2 to H4 breaks the document outline for screen readers and parsers.",
    "Use heading levels in order without gaps.",
    { impact: 0.2, effort: 0.2, autoFixable: true, fixStrategy: "fix_heading_hierarchy" }),
  c("thin_content", "content", "high",
    "Thin content",
    "Too little substance to satisfy the query or to be worth citing.",
    "Expand with specifics, or merge into a stronger page and redirect.",
    { impact: 0.6, effort: 0.7 }),
  c("no_internal_links_out", "content", "medium",
    "Page links to nothing internally",
    "A page that links nowhere is a dead end for both users and authority flow.",
    "Add contextual links to the most relevant related pages.",
    { impact: 0.35, effort: 0.2, autoFixable: true, fixStrategy: "add_internal_link" }),
  c("content_stale", "content", "medium",
    "Content has not been updated in over 18 months",
    "Freshness matters for queries where the answer changes, and stale pages decay.",
    "Refresh the facts, dates and examples, then update the modified date.",
    { impact: 0.45, effort: 0.5 }),
  c("keyword_cannibalisation", "content", "medium",
    "Several pages target the same query",
    "Pages competing for one query split their signals and neither wins.",
    "Pick the page that should rank, and point the others at it with links or a redirect.",
    { impact: 0.5, effort: 0.4 }),
  c("no_meaningful_headings", "content", "low",
    "Headings carry no topical information",
    "Generic headings tell neither a reader nor a parser what the section covers.",
    "Rewrite headings to state what the section answers.",
    { impact: 0.25, effort: 0.2, autoFixable: true, fixStrategy: "rewrite_headings" }),

  /* -- images ------------------------------------------------------------- */
  c("image_alt_missing", "content", "medium",
    "Image without alt text",
    "Alt text is an accessibility requirement and the only way image search understands the file.",
    "Describe the image in plain language, or use an empty alt if it is decorative.",
    { impact: 0.3, effort: 0.1, autoFixable: true, fixStrategy: "write_alt_text" }),
  c("image_legacy_format", "performance", "low",
    "Image uses a legacy format",
    "WebP and AVIF are typically 25 to 50 percent smaller at the same quality.",
    "Convert to WebP or AVIF with a fallback.",
    { impact: 0.25, effort: 0.3, autoFixable: true, fixStrategy: "optimise_image" }),
  c("image_no_dimensions", "performance", "low",
    "Image has no width and height",
    "Missing dimensions cause layout shift as the image loads.",
    "Set explicit width and height attributes.",
    { impact: 0.25, effort: 0.1, autoFixable: true, fixStrategy: "set_image_dimensions" }),
  c("image_no_lazy_loading", "performance", "low",
    "Below-the-fold images load eagerly",
    "Every eager image competes with the hero for bandwidth on first paint.",
    "Add loading=lazy to images below the fold, and never to the hero.",
    { impact: 0.2, effort: 0.1, autoFixable: true, fixStrategy: "set_image_loading" }),

  /* -- performance -------------------------------------------------------- */
  c("slow_response", "performance", "high",
    "Server response is slow",
    "Time to first byte sits in front of every other performance metric.",
    "Cache at the edge, or fix whatever the server is doing before it answers.",
    { impact: 0.55, effort: 0.5 }),
  c("heavy_page", "performance", "medium",
    "Page weight is large",
    "Weight is the part of Core Web Vitals you control without touching the framework.",
    "Compress the HTML, split the JavaScript, and serve images at display size.",
    { impact: 0.4, effort: 0.5 }),
  c("excessive_javascript", "performance", "medium",
    "Very large JavaScript payload",
    "Parse and execution time on mid-range phones is where most performance is lost.",
    "Code-split, defer what is not needed for first paint, drop unused libraries.",
    { impact: 0.4, effort: 0.7 }),
  c("render_blocking_resources", "performance", "medium",
    "Render-blocking stylesheets and scripts",
    "Anything parsed before first paint delays first paint.",
    "Inline the critical CSS, defer the rest, and add async or defer to scripts.",
    { impact: 0.4, effort: 0.5 }),

  /* -- schema ------------------------------------------------------------- */
  c("schema_missing", "schema", "medium",
    "No structured data",
    "Without schema the page cannot earn rich results and is harder for answer engines to parse.",
    "Add the JSON-LD type that matches this page: Article, Product, LocalBusiness, FAQPage.",
    { impact: 0.45, effort: 0.3, autoFixable: true, fixStrategy: "generate_schema" }),
  c("schema_invalid", "schema", "high",
    "Structured data is invalid",
    "Invalid JSON-LD is ignored entirely, so the effort already spent earns nothing.",
    "Fix the syntax or the missing required properties.",
    { impact: 0.5, effort: 0.3, autoFixable: true, fixStrategy: "fix_schema" }),
  c("schema_missing_required", "schema", "medium",
    "Structured data is missing required properties",
    "Rich results need the required fields; without them the markup is decorative.",
    "Add the properties this type requires.",
    { impact: 0.4, effort: 0.2, autoFixable: true, fixStrategy: "fix_schema" }),
  c("schema_contradicts_page", "schema", "high",
    "Structured data does not match the visible page",
    "Markup that describes content a user cannot see is a manual action risk.",
    "Make the markup describe exactly what is on the page.",
    { impact: 0.7, effort: 0.3 }),
  c("no_organization_schema", "schema", "medium",
    "No Organization or LocalBusiness markup on the homepage",
    "This is the markup that tells every engine who the brand is.",
    "Add Organization schema with logo, sameAs profiles and contact details.",
    { impact: 0.5, effort: 0.2, autoFixable: true, fixStrategy: "generate_schema" }),
  c("no_breadcrumb_schema", "schema", "low",
    "No breadcrumb markup",
    "Breadcrumbs replace the URL in the result and show where the page sits.",
    "Add BreadcrumbList JSON-LD matching the visible navigation.",
    { impact: 0.25, effort: 0.2, autoFixable: true, fixStrategy: "generate_schema" }),

  /* -- AEO and GEO -------------------------------------------------------- */
  c("ai_crawler_blocked", "aeo", "high",
    "AI crawlers are blocked",
    "Blocking GPTBot, ClaudeBot, PerplexityBot and friends removes the site from AI answers.",
    "Decide deliberately: allow the crawlers you want citations from.",
    { impact: 0.7, effort: 0.2, autoFixable: true, fixStrategy: "update_robots_ai" }),
  c("no_direct_answer", "aeo", "medium",
    "Page does not answer its question directly",
    "Answer engines quote the passage that states the answer plainly near the top.",
    "Open with a two to three sentence direct answer before the detail.",
    { impact: 0.5, effort: 0.4, autoFixable: true, fixStrategy: "add_answer_block" }),
  c("no_citable_facts", "aeo", "medium",
    "No citable facts or data",
    "Models cite pages that contain specific numbers, dates and named sources.",
    "Add original data, specific figures and sourced statements.",
    { impact: 0.45, effort: 0.6 }),
  c("missing_llms_txt", "aeo", "low",
    "No llms.txt",
    "An llms.txt gives answer engines a curated map of what matters on the site.",
    "Publish /llms.txt listing the canonical pages and what each covers.",
    { impact: 0.2, effort: 0.2, autoFixable: true, fixStrategy: "generate_llms_txt" }),
  c("no_author_attribution", "aeo", "medium",
    "No identifiable author",
    "Experience and expertise cannot be assessed without a real, credentialed author.",
    "Attribute the page to a named author with a linked bio and credentials.",
    { impact: 0.45, effort: 0.4 }),
  c("entity_unclear", "aeo", "medium",
    "The brand entity is not defined",
    "Answer engines resolve brands through consistent entity signals, not prose.",
    "Add Organization schema with sameAs links to the profiles that describe you.",
    { impact: 0.4, effort: 0.3, autoFixable: true, fixStrategy: "generate_schema" }),
  c("no_faq_structure", "aeo", "low",
    "Questions are answered without FAQ structure",
    "A question heading followed by a short answer is the shape an engine lifts.",
    "Group the questions into an FAQ section with FAQPage markup.",
    { impact: 0.3, effort: 0.2, autoFixable: true, fixStrategy: "generate_schema" }),
  c("content_not_extractable", "aeo", "high",
    "Body content is not present in the served HTML",
    "If the HTML arrives empty, an answer engine that does not execute JavaScript sees nothing.",
    "Server-render the content, or pre-render it for crawlers.",
    { impact: 0.8, effort: 0.7 }),

  /* -- local -------------------------------------------------------------- */
  c("nap_inconsistent", "local", "high",
    "Business name, address or phone is inconsistent",
    "Conflicting NAP data undermines the confidence that drives map pack ranking.",
    "Standardise one exact format and correct every listing to match.",
    { impact: 0.6, effort: 0.4 }),
  c("nap_missing", "local", "high",
    "Address and phone are not on the site",
    "A local business without visible contact details cannot be verified by anyone.",
    "Put the full name, address and phone in the footer of every page.",
    { impact: 0.6, effort: 0.2, autoFixable: true, fixStrategy: "add_nap" }),
  c("gbp_incomplete", "local", "high",
    "Google Business Profile is incomplete",
    "Profile completeness correlates directly with map pack visibility.",
    "Fill categories, services, hours, attributes and photos.",
    { impact: 0.6, effort: 0.3, autoFixable: true, fixStrategy: "update_gbp" }),
  c("gbp_no_recent_posts", "local", "medium",
    "No recent Google Business Profile posts",
    "An inactive profile signals an inactive business to both users and the ranking system.",
    "Post weekly: offers, updates, events.",
    { impact: 0.35, effort: 0.2, autoFixable: true, fixStrategy: "draft_gbp_post" }),
  c("reviews_unanswered", "local", "medium",
    "Reviews have no response",
    "Responding is a documented local ranking factor and changes how prospects read the profile.",
    "Reply to every review, positive and negative.",
    { impact: 0.4, effort: 0.2, autoFixable: true, fixStrategy: "draft_review_reply" }),
  c("missing_location_page", "local", "medium",
    "No landing page for this location",
    "Each location needs a page to rank for its own city and to link the profile to.",
    "Build a location page with unique local content, an embedded map and LocalBusiness schema.",
    { impact: 0.5, effort: 0.6, autoFixable: true, fixStrategy: "draft_location_page" }),
  c("no_local_schema", "local", "medium",
    "No LocalBusiness markup",
    "LocalBusiness schema carries the hours, address and geo that map surfaces read.",
    "Add LocalBusiness JSON-LD with address, geo, hours and priceRange.",
    { impact: 0.45, effort: 0.2, autoFixable: true, fixStrategy: "generate_schema" }),
  c("citation_missing", "local", "low",
    "Missing directory citation",
    "Citations on authoritative directories reinforce the entity and its NAP.",
    "Claim and complete the listing.",
    { impact: 0.25, effort: 0.3 }),

  /* -- off page ----------------------------------------------------------- */
  c("toxic_backlinks", "offpage", "high",
    "Toxic backlinks detected",
    "Links from spam networks can drag a site down and occasionally trigger a manual action.",
    "Verify before acting, then disavow only what is clearly manipulative.",
    { impact: 0.5, effort: 0.4 }),
  c("lost_backlinks", "offpage", "medium",
    "Backlinks lost",
    "Losing earned links reverses the authority that earned the rankings.",
    "Check whether the page changed or was removed, then ask for reinstatement.",
    { impact: 0.4, effort: 0.4 }),
  c("unlinked_mention", "offpage", "medium",
    "Brand mentioned without a link",
    "The hardest part, the coverage, already happened. The link is one email away.",
    "Ask the author to link the mention.",
    { impact: 0.4, effort: 0.2 }),
  c("authority_gap", "offpage", "medium",
    "Competitors have substantially more referring domains",
    "For competitive queries, link authority is often the binding constraint.",
    "Build a linkable asset and run targeted outreach.",
    { impact: 0.55, effort: 0.8 }),
  c("no_linkable_asset", "offpage", "medium",
    "Nothing on the site is worth linking to",
    "Outreach fails without an asset: original data, a tool, or a genuine reference.",
    "Publish one original research piece, calculator or reference guide per quarter.",
    { impact: 0.5, effort: 0.8 }),
  c("backlinks_not_connected", "offpage", "high",
    "No backlink data source connected",
    "Link work is guesswork until the referring domain set is known.",
    "Connect Search Console, or a link index such as DataForSEO, Ahrefs or Majestic.",
    { impact: 0.6, effort: 0.1 }),

  /* -- international ------------------------------------------------------ */
  c("hreflang_missing_return", "international", "high",
    "Hreflang has no return tag",
    "Hreflang is only honoured when every version points back at the others.",
    "Add reciprocal hreflang annotations on all versions.",
    { impact: 0.5, effort: 0.3, autoFixable: true, fixStrategy: "fix_hreflang" }),
  c("hreflang_invalid_code", "international", "medium",
    "Invalid hreflang language or region code",
    "An invalid code is ignored, so the targeting silently does nothing.",
    "Use valid ISO 639-1 language and ISO 3166-1 Alpha 2 region codes.",
    { impact: 0.35, effort: 0.2, autoFixable: true, fixStrategy: "fix_hreflang" }),
  c("no_x_default", "international", "low",
    "No x-default hreflang",
    "Users outside your targeted regions get an arbitrary version.",
    "Add an x-default pointing at the language selector or the global version.",
    { impact: 0.2, effort: 0.2, autoFixable: true, fixStrategy: "fix_hreflang" }),

  /* -- ecommerce ---------------------------------------------------------- */
  c("product_schema_incomplete", "ecommerce", "high",
    "Product markup is missing merchant listing fields",
    "Without price, availability and identifiers the product cannot appear in shopping surfaces.",
    "Add offers, price, priceCurrency, availability and a GTIN or MPN.",
    { impact: 0.6, effort: 0.3, autoFixable: true, fixStrategy: "fix_schema" }),
  c("faceted_nav_crawl_waste", "ecommerce", "high",
    "Faceted navigation is generating crawlable duplicate URLs",
    "Filter combinations can multiply into millions of near-identical pages.",
    "Canonicalise or block the combinations that have no search demand.",
    { impact: 0.6, effort: 0.5 }),
  c("no_product_reviews", "ecommerce", "medium",
    "Product pages carry no review markup",
    "Ratings in the result are the single largest click-through lever in shopping.",
    "Collect reviews and mark them up with AggregateRating.",
    { impact: 0.4, effort: 0.4 }),

  /* -- conversion and experience ------------------------------------------ */
  c("no_clear_cta", "ux", "medium",
    "No clear call to action",
    "Traffic that cannot convert is a cost, not a result.",
    "Add one primary action above the fold that matches the page's intent.",
    { impact: 0.5, effort: 0.3 }),
  c("intent_mismatch", "ux", "high",
    "Page format does not match search intent",
    "A product page cannot win an informational query however well it is optimised.",
    "Match the format the ranking results use, or target a different query.",
    { impact: 0.7, effort: 0.6 }),
  c("mobile_unfriendly", "ux", "high",
    "Page is not mobile friendly",
    "Indexing is mobile-first, and most traffic is mobile.",
    "Fix the viewport, tap targets and horizontal overflow.",
    { impact: 0.7, effort: 0.5, autoFixable: true, fixStrategy: "add_viewport" }),
  c("no_social_preview", "ux", "low",
    "No Open Graph or Twitter card",
    "Shared links render as a bare URL, which nobody clicks.",
    "Add og:title, og:description, og:image and a summary_large_image card.",
    { impact: 0.25, effort: 0.1, autoFixable: true, fixStrategy: "generate_og" }),

  /* -- compliance and risk ------------------------------------------------ */
  c("ymyl_no_credentials", "compliance", "high",
    "Health, legal or financial content with no stated credentials",
    "For topics that affect health or money, unqualified advice is both a ranking and a liability problem.",
    "Attribute the content to a qualified reviewer and state the credential.",
    { impact: 0.7, effort: 0.4 }),
  c("unsubstantiated_claim", "compliance", "high",
    "Claim published without substantiation",
    "Unsupported superlatives and performance claims carry regulatory risk in most markets.",
    "Cite the source, soften the claim, or remove it.",
    { impact: 0.5, effort: 0.2 }),
  c("missing_disclosure", "compliance", "medium",
    "Affiliate or sponsored content without disclosure",
    "Undisclosed commercial relationships breach platform policy and advertising law.",
    "Add a clear disclosure above the fold.",
    { impact: 0.5, effort: 0.1, autoFixable: true, fixStrategy: "add_disclosure" }),
  c("no_privacy_policy", "compliance", "medium",
    "No privacy policy found",
    "It is a legal requirement in most markets and a trust signal everywhere.",
    "Publish a privacy policy and link it from the footer.",
    { impact: 0.35, effort: 0.2 }),

  /* -- analytics ---------------------------------------------------------- */
  c("analytics_missing", "analytics", "high",
    "No analytics tag detected",
    "Without measurement, nothing that follows can be attributed or defended.",
    "Install GA4 or your analytics of choice and verify it fires.",
    { impact: 0.6, effort: 0.2 }),
  c("gsc_not_connected", "analytics", "high",
    "Search Console is not connected",
    "Search Console is the only first-party source of query and indexing truth.",
    "Connect the property so the platform can work from real data.",
    { impact: 0.8, effort: 0.1 }),
  c("ga4_not_connected", "analytics", "medium",
    "Analytics is not connected to the platform",
    "Without session and conversion data, the reporting cannot show what the work earned.",
    "Connect GA4 so results are measured rather than asserted.",
    { impact: 0.5, effort: 0.1 }),
  c("conversion_tracking_missing", "analytics", "medium",
    "No conversion tracking",
    "Ranking without conversion data optimises for the wrong thing.",
    "Define and instrument the actions that represent revenue.",
    { impact: 0.5, effort: 0.4 }),
];

export const CATALOG: Record<string, CheckDef> = Object.fromEntries(
  DEFS.map((d) => [d.code, d]),
);

export const CATALOG_SIZE = DEFS.length;

export function byCategory(): Record<string, CheckDef[]> {
  const out: Record<string, CheckDef[]> = {};
  const order: Severity[] = ["critical", "high", "medium", "low", "info"];
  for (const def of DEFS) (out[def.category] ??= []).push(def);
  for (const list of Object.values(out)) {
    list.sort((a, b) => order.indexOf(a.severity) - order.indexOf(b.severity));
  }
  return out;
}

export const CATEGORY_LABEL: Record<string, string> = {
  technical: "Technical and crawl",
  content: "Content and on-page",
  performance: "Speed and Core Web Vitals",
  schema: "Structured data",
  aeo: "AI answers (AEO and GEO)",
  local: "Local and maps",
  offpage: "Authority and links",
  international: "International targeting",
  ecommerce: "Ecommerce",
  ux: "Experience and conversion",
  compliance: "Compliance and risk",
  analytics: "Measurement",
};
