#!/usr/bin/env python3
"""Generate the browser's copy of the paid desk's reference data.

Four tables decide what the paid desk will and will not do: which platforms
exist and what each demands, which placements an asset must fit, which copy
rules cause rejections, and every way a launch can fail. All four are read by
both engines, and a hand-written second copy drifts. The first thing to drift
would be the list of what we refuse, which is the part the interface makes a
promise out of.

So the Python file is the source and this writes the TypeScript. The same
argument, and the same script shape, as `roster_to_ts.py`. CI fails if the
output is stale.

    python scripts/ads_to_ts.py
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "packages"))

from seoos.analysis.ad_failures import FAILURES  # noqa: E402
from seoos.analysis.ad_policy import RULES, SPECIAL_CATEGORIES  # noqa: E402
from seoos.analysis.ad_specs import PLACEMENTS  # noqa: E402
from seoos.connectors.ads import PLATFORMS  # noqa: E402

OUT = ROOT / "apps" / "web" / "src" / "engine" / "ads.generated.ts"

HEADER = '''/**
 * Generated by scripts/ads_to_ts.py. Do not edit.
 *
 * The browser's copy of the four tables the paid desk turns on: the platforms
 * and what each one demands before it can be written to, the placements an
 * asset has to fit, the copy rules that cause rejections, and every way a
 * launch can fail.
 *
 * Generated rather than hand-written because a second copy drifts, and the
 * first thing to drift is the list of what this desk refuses to do, which is
 * the part the interface makes a promise out of. Run `make docs` after
 * changing connectors/ads.py, analysis/ad_specs.py, analysis/ad_policy.py or
 * analysis/ad_failures.py.
 */

'''


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(w.title() for w in rest)


def ts_object(data: dict, keys: list[str] | None = None) -> str:
    """One object literal, with snake_case keys turned into camelCase."""
    parts = []
    for key, value in data.items():
        if keys is not None and key not in keys:
            continue
        parts.append(f"{camel(key)}: {json.dumps(value, ensure_ascii=False)}")
    return "{ " + ", ".join(parts) + " }"


def main() -> None:
    lines: list[str] = [HEADER]

    # ------------------------------------------------------------ platforms
    lines.append("""export type AdPlatform = {
  key: string;
  name: string;
  /** What the advertiser does. Always one button, never a pasted credential. */
  userAction: string;
  oauthScopes: string[];
  /** What each scope buys, in the language of the person reading the consent screen. */
  scopeReasons: string[];
  /** What we must clear before that button works for anyone but us. */
  appRequirements: string[];
  reviewTime: string;
  sandbox: string | null;
  writes: string[];
  cannot: string[];
  objectives: string[];
  leadForms: boolean;
  productFeed: boolean;
  offlineConversions: boolean;
  serverEvents: string | null;
  status: string;
  worthIt: string;
};

export const AD_PLATFORMS: AdPlatform[] = [""")
    for p in PLATFORMS:
        lines.append("  " + ts_object(asdict(p)) + ",")
    lines.append("];\n")

    # ----------------------------------------------------------- placements
    lines.append("""export type Placement = {
  key: string;
  platform: string;
  name: string;
  width: number;
  height: number;
  /** Fractions of the frame covered by the platform's own interface. */
  safeTop: number;
  safeBottom: number;
  safeLeft: number;
  safeRight: number;
  maxMb: number;
  formats: string[];
  video: boolean;
  /** Field name to maximum characters, before the platform truncates silently. */
  textLimits: Record<string, number>;
  note: string;
};

export const PLACEMENTS: Placement[] = [""")
    for place in PLACEMENTS:
        lines.append("  " + ts_object(asdict(place)) + ",")
    lines.append("];\n")

    # --------------------------------------------------------- policy rules
    lines.append("""export type PolicyRule = {
  key: string;
  /** Source and flags, so the browser can rebuild the same expression. */
  pattern: string;
  flags: string;
  severity: "block" | "warn";
  /** The platform's own reasoning, so an advertiser can argue with it. */
  why: string;
  fix: string;
  platforms: string[];
};

export const POLICY_RULES: PolicyRule[] = [""")
    for rule in RULES:
        flags = "i" if rule.pattern.flags & 2 else ""
        lines.append(
            "  { "
            + f"key: {json.dumps(rule.key)}, "
            + f"pattern: {json.dumps(rule.pattern.pattern)}, "
            + f"flags: {json.dumps(flags)}, "
            + f"severity: {json.dumps(rule.severity)}, "
            + f"why: {json.dumps(rule.why, ensure_ascii=False)}, "
            + f"fix: {json.dumps(rule.fix, ensure_ascii=False)}, "
            + f"platforms: {json.dumps(list(rule.platforms))}"
            + " },"
        )
    lines.append("];\n")

    lines.append("/** Restricted categories. Wider than the other rules on purpose: see ad_policy.py. */")
    lines.append("export const SPECIAL_CATEGORIES: { name: string; pattern: string; flags: string }[] = [")
    for name, pattern in SPECIAL_CATEGORIES.items():
        flags = "i" if pattern.flags & 2 else ""
        lines.append(
            f"  {{ name: {json.dumps(name)}, pattern: {json.dumps(pattern.pattern)}, flags: {json.dumps(flags)} }},"
        )
    lines.append("];\n")

    # -------------------------------------------------------------- failures
    lines.append("""export type AdFailure = {
  code: string;
  stage: "connect" | "plan" | "build" | "launch" | "run" | "report";
  severity: "money" | "blocked" | "degraded" | "cosmetic";
  what: string;
  /** How the software knows, without a person looking. */
  detect: string;
  /** What happens automatically. Never "log and continue". */
  respond: string;
  /** What the person reads. Written for them, not for us. */
  tell: string;
  /** The route that still ships. Empty where there genuinely is not one. */
  fallback: string;
  platforms: string[];
};

export const AD_FAILURES: AdFailure[] = [""")
    for f in FAILURES:
        lines.append("  " + ts_object(asdict(f)) + ",")
    lines.append("];\n")

    lines.append("""export const AD_PLATFORM_BY_KEY = new Map(AD_PLATFORMS.map((p) => [p.key, p]));
export const PLACEMENT_BY_KEY = new Map(PLACEMENTS.map((p) => [p.key, p]));
export const FAILURE_BY_CODE = new Map(AD_FAILURES.map((f) => [f.code, f]));
""")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"{OUT.relative_to(ROOT)}: {len(PLATFORMS)} platforms, {len(PLACEMENTS)} placements, "
        f"{len(RULES)} policy rules, {len(FAILURES)} failures"
    )


if __name__ == "__main__":
    main()
