#!/usr/bin/env node
/**
 * Bake the commit and the build time into a module, before the build.
 *
 * The first version of the version endpoint read `process.env` inside a
 * server route, which looked right and was wrong: those variables exist in
 * the build container, and a route evaluates them at runtime on the Worker,
 * where they are gone. It answered "unknown" on every deploy. `new Date()` at
 * module scope had the same shape of error, reporting when the isolate
 * started rather than when the bundle was made.
 *
 * So the value is resolved here, once, while the build still has a git
 * checkout and the CI variables, and written to a file the bundle inlines.
 *
 *   node scripts/build-info.mjs
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "apps/web/src/lib/build-info.generated.ts");

function commit() {
  // Cloudflare Workers Builds, Cloudflare Pages, GitHub Actions, then git.
  const fromEnv =
    process.env.WORKERS_CI_COMMIT_SHA ||
    process.env.CF_PAGES_COMMIT_SHA ||
    process.env.GITHUB_SHA ||
    "";
  if (fromEnv) return fromEnv;
  try {
    return execSync("git rev-parse HEAD", { cwd: ROOT, encoding: "utf8" }).trim();
  } catch {
    // A tarball with no git history is a real situation, and "unknown" is a
    // true answer. A fabricated one would defeat the whole point of this file.
    return "";
  }
}

function branch() {
  const fromEnv = process.env.WORKERS_CI_BRANCH || process.env.CF_PAGES_BRANCH || "";
  if (fromEnv) return fromEnv;
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", { cwd: ROOT, encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

const sha = commit();

writeFileSync(
  OUT,
  `/**
 * Generated by scripts/build-info.mjs. Do not edit.
 *
 * Resolved while the build still had a git checkout and the CI environment,
 * because a server route reading process.env evaluates it at runtime on the
 * Worker, where none of that exists.
 */

export const BUILD_COMMIT: string = ${JSON.stringify(sha ? sha.slice(0, 12) : "unknown")};
export const BUILD_BRANCH: string = ${JSON.stringify(branch() || "unknown")};
export const BUILD_AT: string = ${JSON.stringify(new Date().toISOString())};
`,
  "utf8",
);

console.log(`build-info: ${sha ? sha.slice(0, 12) : "unknown"} on ${branch() || "unknown"}`);
