#!/usr/bin/env python3
"""Generate the reference documentation from the code itself.

Hand-written reference docs drift the moment someone adds a tool. These are
derived from the live registries, so `make docs` after any change keeps
them true. CI can diff the output to catch a stale commit.

    python scripts/generate_reference.py
"""

from __future__ import annotations

import inspect
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reference"
sys.path.insert(0, str(ROOT / "packages"))

HEADER = (
    "<!-- Generated by scripts/generate_reference.py. Do not edit by hand; "
    "run `make docs` after changing the code. -->\n\n"
)


def write(name: str, body: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(HEADER + body.rstrip() + "\n", encoding="utf-8")
    print(f"  docs/reference/{name}")


def esc(text: str | None) -> str:
    """Make a value safe inside a markdown table cell."""
    if text is None:
        return ""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


# ---------------------------------------------------------------------------


def gen_tools() -> None:
    from seoos.tools import load_all_tools

    registry = load_all_tools()
    tools = registry.all()

    by_category: dict[str, list] = {}
    for tool in tools:
        by_category.setdefault(tool.category, []).append(tool)

    lines = [
        "# Tool reference",
        "",
        "A tool is the only way an agent touches the world. Everything an agent",
        "can do is in this list; nothing outside it is reachable.",
        "",
        f"**{len(tools)} tools** across {len(by_category)} categories. "
        f"{sum(1 for t in tools if t.mutates)} of them change state.",
        "",
        "## How to read this",
        "",
        "- **Mutates** means the call changes something. Those go through the",
        "  approval policy before they run and leave an audit row after.",
        "- **Risk** drives the autonomy floor. `critical` can never run",
        "  unattended at any autonomy level.",
        "- **Auto from** is the lowest autonomy level at which the tool runs",
        "  without a human. Blank means it is derived from risk.",
        "",
        "| Risk | Runs unattended from |",
        "|---|---|",
        "| `internal` | `observe` (platform records only, never the client's site) |",
        "| `none` / `low` | `assisted` |",
        "| `medium` | `managed` |",
        "| `high` | `autopilot` |",
        "| `critical` | never |",
        "",
    ]

    for category in sorted(by_category):
        lines += [f"## {category}", ""]
        for tool in sorted(by_category[category], key=lambda t: t.name):
            summary = (tool.description or "").strip().split("\n\n")[0]
            lines += [f"### `{tool.name}`", "", summary, ""]

            facts = [f"**Mutates:** {'yes' if tool.mutates else 'no'}",
                     f"**Risk:** `{tool.risk}`"]
            if tool.auto_from:
                facts.append(f"**Runs unattended from:** `{tool.auto_from}`")
            if tool.approval_type:
                facts.append(f"**Approval type:** `{tool.approval_type}`")
            if tool.tags:
                facts.append(f"**Tags:** {', '.join(f'`{t}`' for t in tool.tags)}")
            if tool.cost_hint_usd:
                facts.append(f"**Typical cost:** about ${tool.cost_hint_usd:.4f}")
            lines += [" · ".join(facts), ""]

            props = (tool.parameters or {}).get("properties") or {}
            required = set((tool.parameters or {}).get("required") or [])
            if props:
                lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
                for key, spec in props.items():
                    kind = spec.get("type", "any")
                    if spec.get("enum"):
                        kind = " \\| ".join(f"`{v}`" for v in spec["enum"])
                    lines.append(
                        f"| `{key}` | {kind} | {'yes' if key in required else 'no'} "
                        f"| {esc(spec.get('description'))} |"
                    )
                lines.append("")
            else:
                lines += ["Takes no parameters.", ""]

    write("TOOLS.md", "\n".join(lines))


def gen_checks() -> None:
    from seoos.analysis.findings import CATALOG, catalog_by_category

    by_category = catalog_by_category()
    lines = [
        "# Check catalogue",
        "",
        "Every check the audit runs. All of them are deterministic: no model is",
        "involved, so a given page always produces the same findings and an",
        "audit costs nothing to produce.",
        "",
        f"**{len(CATALOG)} checks** across {len(by_category)} categories.",
        "",
        "## Prioritisation",
        "",
        "Findings are ranked by `impact x confidence / effort`, scaled by how",
        "many pages they affect. The inputs are in the table so the ranking can",
        "be argued with rather than taken on faith.",
        "",
        "**Fix** means the platform can apply the change itself when autonomy",
        "allows. Everything else needs a person or a developer.",
        "",
    ]

    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    for category in sorted(by_category):
        checks = sorted(
            by_category[category], key=lambda c: (severity_order.get(c.severity, 9), c.code)
        )
        lines += [
            f"## {category}",
            "",
            "| Code | Severity | Check | Impact | Effort | Fix |",
            "|---|---|---|---|---|---|",
        ]
        for check in checks:
            lines.append(
                f"| `{check.code}` | {check.severity} | {esc(check.title)} "
                f"| {check.impact:.2f} | {check.effort:.2f} "
                f"| {'auto' if check.auto_fixable else '-'} |"
            )
        lines.append("")
        for check in checks:
            lines += [
                f"**`{check.code}`** — {esc(check.title)}",
                "",
                f"- *Why it matters:* {check.why}",
                f"- *What to do:* {check.recommendation}",
                "",
            ]

    write("CHECKS.md", "\n".join(lines))


def gen_agents() -> None:
    from seoos.agents.registry import get_registry

    registry = get_registry()
    agents = registry.all()
    departments: dict[str, list] = {}
    for spec in agents:
        departments.setdefault(spec.department, []).append(spec)

    order = [
        "leadership", "strategy", "research", "technical", "content",
        "aeo", "offpage", "local", "commerce", "conversion", "operations",
    ]
    ordered = [d for d in order if d in departments] + [
        d for d in sorted(departments) if d not in order
    ]

    lines = [
        "# Agent reference",
        "",
        f"**{len(agents)} agents** across {len(departments)} departments.",
        "",
        "Each agent is a markdown file in `packages/seoos/agents/roster/`. The",
        "YAML front matter is the contract the runtime enforces: which tools it",
        "may call, which model tier it runs on, who it may delegate to, and what",
        "it costs at most. The body is the operating manual the model reads.",
        "",
        "An agent cannot call a tool it was not given, delegate to an agent not",
        "listed, or exceed its cost ceiling. The roster fails validation at boot",
        "if any of those references are wrong.",
        "",
        "## Org chart",
        "",
        "```",
    ]

    chart = registry.org_chart()

    def render(node: str, depth: int, seen: set[str]) -> None:
        if node in seen:
            return
        seen.add(node)
        for child in sorted(chart.get(node, [])):
            spec = registry.get(child) if registry.has(child) else None
            label = f"{child}" + (f"  ({spec.name})" if spec else "")
            lines.append("  " * depth + "- " + label)
            render(child, depth + 1, seen)

    render("client", 0, set())
    lines += ["```", ""]

    for department in ordered:
        lines += [f"## {department}", ""]
        for spec in sorted(departments[department], key=lambda s: s.key):
            lines += [
                f"### {spec.name}  `{spec.key}`",
                "",
                f"**Role:** {spec.role}",
                "",
                spec.summary,
                "",
                "| | |",
                "|---|---|",
                f"| Model tier | `{spec.model_tier}` |",
                f"| Temperature | {spec.temperature} |",
                f"| Max turns | {spec.max_iterations} |",
                f"| Cost ceiling | ${spec.cost_ceiling_usd:.2f} per run |",
                f"| Reports to | {'`' + spec.reports_to + '`' if spec.reports_to else 'the client'} |",
                f"| Delegates to | {', '.join('`' + d + '`' for d in spec.delegates_to) or 'nobody'} |",
                f"| Tools | {', '.join('`' + t + '`' for t in spec.tools)} |",
                "",
            ]
            if spec.never:
                lines += ["**Never:**", ""] + [f"- {n}" for n in spec.never] + [""]
            if spec.guardrails:
                lines += ["**Guardrails:**", ""] + [f"- {g}" for g in spec.guardrails] + [""]
            if spec.success_criteria:
                lines += ["**Done looks like:**", ""] + [
                    f"- {s}" for s in spec.success_criteria
                ] + [""]

    write("AGENTS.md", "\n".join(lines))


def gen_missions() -> None:
    from seoos.missions.registry import get_mission_registry

    registry = get_mission_registry()
    missions = registry.all()

    lines = [
        "# Mission reference",
        "",
        f"**{len(missions)} missions.** A mission is a declarative workflow in",
        "`packages/seoos/missions/workflows/`. Its steps are either deterministic",
        "tool calls or agents, arranged by dependency. Steps whose dependencies",
        "are all satisfied run concurrently, in waves.",
        "",
        "State is shared through a blackboard that is committed to the database",
        "at every wave boundary, so a mission interrupted by a deploy resumes",
        "rather than restarting.",
        "",
        "## Summary",
        "",
        "| Mission | Steps | Waves | Budget | Schedule | Applies to |",
        "|---|---|---|---|---|---|",
    ]
    for spec in missions:
        waves = len(spec.execution_order())
        applies = ", ".join(spec.business_types) if spec.business_types else "any business"
        lines.append(
            f"| `{spec.key}` | {len(spec.steps)} | {waves} | ${spec.budget_usd:.0f} "
            f"| {'`' + spec.schedule_hint + '`' if spec.schedule_hint else 'on demand'} "
            f"| {applies} |"
        )
    lines.append("")

    for spec in missions:
        lines += [
            f"## `{spec.key}` — {spec.name}",
            "",
            spec.description.strip() or "",
            "",
            f"**Budget:** ${spec.budget_usd:.2f} · **Timeout:** {spec.timeout_minutes} min "
            f"· **Concurrency:** {spec.concurrency}"
            + (f" · **Schedule:** `{spec.schedule_hint}`" if spec.schedule_hint else ""),
            "",
        ]
        if spec.requires_capabilities:
            lines += [
                "**Needs:** " + ", ".join(f"`{c}`" for c in spec.requires_capabilities),
                "",
            ]
        lines += ["### Execution order", ""]
        for index, wave in enumerate(spec.execution_order(), start=1):
            names = ", ".join(f"`{s.id}`" for s in wave)
            concurrent = " (concurrent)" if len(wave) > 1 else ""
            lines.append(f"{index}. {names}{concurrent}")
        lines += ["", "### Steps", "",
                  "| Step | Type | Runs | Depends on | Condition | On error |",
                  "|---|---|---|---|---|---|"]
        for step in spec.steps:
            runs = f"`{step.tool}`" if step.tool else (f"`{step.agent}`" if step.agent else "-")
            lines.append(
                f"| `{step.id}` | {step.type} | {runs} "
                f"| {', '.join('`' + n + '`' for n in step.needs) or '-'} "
                f"| {'`' + esc(step.when) + '`' if step.when else '-'} "
                f"| {step.on_error}{' (optional)' if step.optional else ''} |"
            )
        lines.append("")

    write("MISSIONS.md", "\n".join(lines))


def gen_connectors() -> None:
    from seoos.connectors.registry import CONNECTORS, PROVIDER_SPECS, capabilities_for

    lines = [
        "# Connector reference",
        "",
        f"**{len(CONNECTORS)} integrations.** None of them is required: the",
        "platform crawls and audits any public site with nothing connected, and",
        "every capability that is unavailable is reported as unavailable rather",
        "than silently skipped.",
        "",
        "## What each one unlocks",
        "",
        "| Provider | Category | Auth | Unlocks |",
        "|---|---|---|---|",
    ]
    for spec in PROVIDER_SPECS:
        lines.append(
            f"| **{esc(spec.display_name)}** | {spec.category} | `{spec.auth_kind}` "
            f"| {esc(spec.unlocks)} |"
        )
    lines += ["", "## Capability matrix", "",
              "What becomes possible as connections are added.", "",
              "| Capability | Available with nothing connected |", "|---|---|"]
    base = capabilities_for(set())
    everything = capabilities_for(set(CONNECTORS))
    for capability in sorted(everything):
        lines.append(f"| `{capability}` | {'yes' if capability in base else 'no'} |")
    lines.append("")

    for spec in PROVIDER_SPECS:
        lines += [
            f"## {spec.display_name}  `{spec.provider}`",
            "",
            spec.summary,
            "",
            f"**Unlocks:** {spec.unlocks}",
            "",
        ]
        if spec.setup_notes:
            lines += [f"> {spec.setup_notes}", ""]
        if spec.credential_fields:
            lines += ["**Credentials**", "",
                      "| Field | Label | Required | Secret | Notes |", "|---|---|---|---|---|"]
            for field in spec.credential_fields:
                lines.append(
                    f"| `{field.key}` | {esc(field.label)} "
                    f"| {'yes' if field.required else 'no'} "
                    f"| {'yes' if field.secret else 'no'} | {esc(field.help)} |"
                )
            lines.append("")
        if spec.config_fields:
            lines += ["**Configuration**", "",
                      "| Field | Label | Required | Notes |", "|---|---|---|---|"]
            for field in spec.config_fields:
                lines.append(
                    f"| `{field.key}` | {esc(field.label)} "
                    f"| {'yes' if field.required else 'no'} | {esc(field.help)} |"
                )
            lines.append("")
        if spec.docs_url:
            lines += [f"[Provider documentation]({spec.docs_url})", ""]

    others = sorted(set(CONNECTORS) - {s.provider for s in PROVIDER_SPECS})
    if others:
        lines += [
            "## Also implemented",
            "",
            "Available to the code but not yet surfaced in the onboarding UI:",
            "",
        ] + [f"- `{name}`" for name in others] + [""]

    write("CONNECTORS.md", "\n".join(lines))


def gen_data_model() -> None:
    from seoos.core import models  # noqa: F401  (registers the mappers)
    from seoos.core.db import Base

    tables = Base.metadata.tables
    lines = [
        "# Data model",
        "",
        f"**{len(tables)} tables.** Multi-tenant with a shared schema: every",
        "tenant-owned table carries `org_id`, and every load goes through one",
        "choke point that refuses cross-tenant reads.",
        "",
        "Identifiers are UUID4 hex, so rows cannot be enumerated by guessing a",
        "neighbouring integer.",
        "",
        "## Tables",
        "",
        "| Table | Columns | Purpose |",
        "|---|---|---|",
    ]
    purposes = {
        "orgs": "A customer. Everything else hangs off this",
        "users": "A person who logs in",
        "memberships": "Which people belong to which org, and with what role",
        "sites": "One website under management; the unit everything is scoped to",
        "api_keys": "Programmatic access for a customer's own automation",
        "audit_log": "Every state change, attributable and reversible",
        "integrations": "A connected account and its health",
        "credentials": "Envelope-encrypted secret material",
        "webhook_endpoints": "Outbound notifications into the client's stack",
        "brand_assets": "What the client uploaded or we found on their site",
        "brand_profiles": "The distilled, versioned voice and positioning",
        "brand_facts": "The claim ledger: what the brand may state in public",
        "crawls": "One crawl run and its summary",
        "pages": "One URL and everything measured about it",
        "findings": "A problem or opportunity, deduplicated by fingerprint",
        "clusters": "A topic cluster: one pillar and its supporting pages",
        "keywords": "A tracked query with volume, intent and target",
        "rankings": "Position over time",
        "competitors": "Who actually competes for this site's queries",
        "ai_visibility_checks": "Whether an answer engine mentioned or cited the brand",
        "content_items": "The pipeline from idea to published page",
        "content_versions": "Immutable snapshot at every transition",
        "content_performance": "What a published page actually did",
        "media_assets": "Images and diagrams, with provenance",
        "backlinks": "Inbound links and their health",
        "link_prospects": "A qualified opportunity, scored before any effort",
        "outreach_threads": "A conversation with one prospect",
        "outreach_messages": "The drafted and sent messages",
        "locations": "A physical location and its Business Profile",
        "reviews": "A review and its drafted reply",
        "gbp_posts": "Business Profile posts",
        "citations": "Directory listings and NAP consistency",
        "mission_runs": "One execution of a workflow, with its blackboard and cost",
        "agent_runs": "One specialist doing one job",
        "tool_calls": "Every external action; the forensic record",
        "approvals": "The client's entire workload, and the action to replay",
        "schedules": "Recurring missions, leased so two workers never collide",
        "reports": "Generated deliverables, including the always-current audit",
        "cost_ledger": "Every dollar, attributed to a site and a run",
        "resolutions": "Institutional memory, so nothing is solved twice",
        "experiments": "Split tests with a control group",
        "kpi_snapshots": "Daily facts for trends and regression detection",
        "notifications": "What the client is told, and through which channel",
    }
    for name in sorted(tables):
        lines.append(
            f"| `{name}` | {len(tables[name].columns)} | {purposes.get(name, '')} |"
        )
    lines.append("")

    for name in sorted(tables):
        table = tables[name]
        lines += [
            f"## `{name}`",
            "",
            purposes.get(name, ""),
            "",
            "| Column | Type | Null | Default | Notes |",
            "|---|---|---|---|---|",
        ]
        for column in table.columns:
            notes = []
            if column.primary_key:
                notes.append("primary key")
            if column.foreign_keys:
                notes.append(
                    "→ " + ", ".join(f"`{fk.target_fullname}`" for fk in column.foreign_keys)
                )
            if column.index:
                notes.append("indexed")
            if column.unique:
                notes.append("unique")
            default = ""
            if column.default is not None and not callable(getattr(column.default, "arg", None)):
                default = f"`{column.default.arg}`"
            lines.append(
                f"| `{column.name}` | {esc(str(column.type))} "
                f"| {'yes' if column.nullable else 'no'} | {default} | {', '.join(notes)} |"
            )
        constraints = [
            c for c in table.constraints
            if c.__class__.__name__ == "UniqueConstraint" and c.columns
        ]
        if constraints:
            lines += [""] + [
                "**Unique:** " + ", ".join(
                    "(" + ", ".join(f"`{col.name}`" for col in c.columns) + ")"
                    for c in constraints
                )
            ]
        if table.indexes:
            lines += [
                "",
                "**Indexes:** " + ", ".join(
                    "`" + i.name + "`" for i in sorted(table.indexes, key=lambda i: i.name or "")
                ),
            ]
        lines.append("")

    write("DATA-MODEL.md", "\n".join(lines))


def gen_api() -> None:
    from seoos.api.app import create_app

    app = create_app()
    schema = app.openapi()

    lines = [
        "# API reference",
        "",
        "All endpoints are under `/api/v1` unless noted. Every one requires",
        "authentication: a session bearer token from `/auth/login`, or an",
        "`X-API-Key` header for a customer's own automation.",
        "",
        "Cross-tenant reads return **404**, not 403, so an identifier cannot be",
        "confirmed by probing.",
        "",
        "An interactive schema is served at `/docs` outside production.",
        "",
        "## Endpoints",
        "",
        "| Method | Path | Purpose |",
        "|---|---|---|",
    ]
    rows = []
    for path, methods in schema.get("paths", {}).items():
        for method, spec in methods.items():
            if method.lower() not in ("get", "post", "patch", "put", "delete"):
                continue
            summary = spec.get("summary") or spec.get("operationId", "")
            rows.append((path, method.upper(), summary))
    for path, method, summary in sorted(rows):
        lines.append(f"| `{method}` | `{path}` | {esc(summary)} |")
    lines.append("")

    lines += [
        "## Roles",
        "",
        "| Role | Can |",
        "|---|---|",
        "| `viewer` | Read everything in the org |",
        "| `approver` | Also decide approvals and review content |",
        "| `editor` | Also create sites, edit content and set schedules |",
        "| `admin` | Also connect and disconnect integrations |",
        "| `owner` | Everything |",
        "",
        "## Error shape",
        "",
        "Domain errors carry a machine-readable code so a client can branch on",
        "it rather than parse prose.",
        "",
        "```json",
        '{ "code": "budget_exceeded", "message": "...", "context": {} }',
        "```",
        "",
        "| Code | Status | Meaning |",
        "|---|---|---|",
    ]
    from seoos.core import errors as error_module

    for _name, obj in sorted(vars(error_module).items()):
        if (
            inspect.isclass(obj)
            and issubclass(obj, error_module.SeoOSError)
            and obj is not error_module.SeoOSError
        ):
            doc = (obj.__doc__ or "").strip().split("\n")[0]
            lines.append(f"| `{obj.code}` | {obj.http_status} | {esc(doc)} |")
    lines.append("")

    write("API.md", "\n".join(lines))
    (OUT / "openapi.json").write_text(json.dumps(schema, indent=2), encoding="utf-8")
    print("  docs/reference/openapi.json")


def gen_configuration() -> None:
    from seoos.core.config import Settings

    lines = [
        "# Configuration reference",
        "",
        "Everything is environment-driven, prefixed `SEOOS_`, so the same image",
        "runs locally, in CI and in production.",
        "",
        "**Nothing below is required to start.** With an empty environment the",
        "platform runs on SQLite, crawls and audits any public site, and marks",
        "generative steps as degraded rather than failing.",
        "",
        "| Variable | Type | Default | Purpose |",
        "|---|---|---|---|",
    ]
    purposes = {
        "master_key": "Encrypts every tenant credential. Losing it makes them unrecoverable",
        "jwt_secret": "Signs session tokens",
        "allow_insecure_dev_keys": "Set false in production so a missing key is a hard failure",
        "database_url": "SQLite for development, Postgres for anything concurrent",
        "default_llm_provider": "Which provider to try first; a tenant's own key still wins",
        "max_usd_per_run": "Hard ceiling no mission can exceed",
        "max_usd_per_org_per_day": "Hard ceiling no organisation can exceed",
        "dry_run": "Make every mutating tool a no-op that logs what it would have done",
        "respect_robots_txt": "Honour robots.txt when crawling. Leave this on",
        "crawl_concurrency": "Parallel fetches; also bounded per host",
        "storage_dir": "Where uploaded brand assets are written",
    }
    for name, field in Settings.model_fields.items():
        default = field.default
        if default is None or default == "":
            rendered = "-"
        elif isinstance(default, bool):
            rendered = "`true`" if default else "`false`"
        else:
            rendered = f"`{default}`"
        kind = getattr(field.annotation, "__name__", str(field.annotation))
        kind = kind.replace("Optional[", "").replace("]", "")
        lines.append(
            f"| `SEOOS_{name.upper()}` | {esc(kind)} | {rendered} "
            f"| {purposes.get(name, esc(field.description))} |"
        )
    lines += [
        "",
        "## Generating the keys",
        "",
        "```bash",
        "seoos keygen",
        "```",
        "",
        "Outside development the platform refuses to start without both",
        "`SEOOS_MASTER_KEY` and `SEOOS_JWT_SECRET`.",
        "",
        "## Model providers",
        "",
        "Setting any one of these enables the generative agents. Setting none is",
        "supported: deterministic analysis still runs.",
        "",
        "| Variable | Provider |",
        "|---|---|",
        "| `SEOOS_ANTHROPIC_API_KEY` | Anthropic |",
        "| `SEOOS_OPENAI_API_KEY` | OpenAI |",
        "| `SEOOS_GOOGLE_API_KEY` | Google |",
        "| `SEOOS_OPENROUTER_API_KEY` | OpenRouter |",
        "| `SEOOS_AZURE_OPENAI_API_KEY` + `SEOOS_AZURE_OPENAI_ENDPOINT` | Azure |",
        "| `SEOOS_OLLAMA_BASE_URL` | A local Ollama endpoint |",
        "",
    ]
    write("CONFIGURATION.md", "\n".join(lines))


def main() -> int:
    print("Generating reference documentation:")
    gen_tools()
    gen_checks()
    gen_agents()
    gen_missions()
    gen_connectors()
    gen_data_model()
    gen_api()
    gen_configuration()
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
