#!/usr/bin/env python3
"""Generate the TypeScript roster from the agent specs.

The public deployment runs on Cloudflare Workers, which cannot run Python, so
the browser interface cannot read `packages/seoos/agents/roster/`. It reads
this generated file instead.

Generated rather than hand-written on purpose: a hand-written copy drifts, and
the first thing that drifts is the list of what each agent refuses to do, which
is the part the interface makes a promise out of. Run `make docs` and commit
the result. CI fails if it is stale.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROSTER = ROOT / "packages" / "seoos" / "agents" / "roster"
OUT = ROOT / "apps" / "web" / "src" / "lib" / "roster.generated.ts"

SCALAR = re.compile(r"^([a-z_]+):\s*(.*)$")


def front_matter(text: str) -> dict:
    if not text.startswith("---"):
        raise ValueError("no front matter")
    body = text.split("---", 2)[1]
    data: dict = {}
    key: str | None = None
    for line in body.splitlines():
        if not line.strip():
            continue
        if line.startswith("  - ") and key:
            data.setdefault(key, [])
            if isinstance(data[key], list):
                data[key].append(line[4:].strip())
            continue
        m = SCALAR.match(line)
        if not m:
            continue
        key, value = m.group(1), m.group(2).strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            data[key] = [v.strip() for v in inner.split(",") if v.strip()]
        elif value:
            data[key] = value
        else:
            data[key] = []
    return data


def main() -> int:
    agents = []
    for path in sorted(ROSTER.glob("*.md")):
        fm = front_matter(path.read_text(encoding="utf-8"))
        guardrails = fm.get("guardrails") or []
        agents.append({
            "key": fm["key"],
            "name": fm["name"],
            # The spec's own one-line statement of what this agent owns.
            "role": fm.get("role", ""),
            "department": fm.get("department", ""),
            "reportsTo": fm.get("reports_to", ""),
            # The first guardrail is the one the spec leads with, so it is the
            # one the interface prints. The rest are on the agent's own page.
            "never": guardrails[0] if guardrails else "",
            "guardrails": guardrails,
            "tools": len(fm.get("tools") or []),
            "delegatesTo": fm.get("delegates_to") or [],
        })

    header = (
        "/*\n"
        " * Generated by scripts/roster_to_ts.py. Do not edit by hand.\n"
        " *\n"
        " * The source of truth is packages/seoos/agents/roster/*.md. Cloudflare\n"
        " * Workers cannot run Python, so the browser interface reads this copy of\n"
        " * the roster rather than the specs themselves. Run `make docs` after\n"
        " * changing a spec, and commit the result.\n"
        " */\n\n"
        "export type RosterAgent = {\n"
        "  key: string;\n"
        "  name: string;\n"
        "  /** What this agent owns, from the spec's own role line. */\n"
        "  role: string;\n"
        "  department: string;\n"
        "  reportsTo: string;\n"
        "  /** The first guardrail. The interface makes a promise out of it. */\n"
        "  never: string;\n"
        "  guardrails: string[];\n"
        "  tools: number;\n"
        "  delegatesTo: string[];\n"
        "};\n\n"
        f"export const ROSTER_COUNT = {len(agents)};\n\n"
        "export const ROSTER: RosterAgent[] = "
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + json.dumps(agents, indent=2, ensure_ascii=False) + ";\n", encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(agents)} agents")
    return 0


if __name__ == "__main__":
    sys.exit(main())
