"use client";

/**
 * Taking an approved change to the live site.
 *
 * The browser holds the approval queue, because that is where the audit that
 * produced it lives. Publishing has to happen on the server, because that is
 * where the credential is. So an approval crosses over at the moment someone
 * presses Publish and not before: it is written to the server's own approvals
 * table, marked approved there, and then published. Three calls rather than
 * one, deliberately, so the record separates what was decided from what the
 * decision caused.
 *
 * Nothing here invents a mapping. The browser sends the URL and the field; the
 * server resolves it against the live site and refuses rather than guessing.
 */

import type { ApprovalRecord } from "./store";
import { post } from "./session";

export type PublishField = "post_title" | "post_excerpt" | "meta_description";

export type PublishOutcome = {
  ok: boolean;
  message: string;
  before: string | null;
  after: string | null;
};

/**
 * Which live field a fix belongs in.
 *
 * Returns null for anything the CMS API cannot write, which is most of the
 * technical findings: robots.txt is generated by WordPress at request time,
 * canonicals come from the theme, and a redirect is a server rule. Those stay
 * copy-and-paste, and the screen says so rather than offering a button that
 * would fail.
 */
export function fieldFor(approval: ApprovalRecord): PublishField | null {
  const label = (approval.fix?.label ?? "").toLowerCase();
  const kind = approval.kind.toLowerCase();
  if (label.includes("meta description") || kind.includes("meta_description")) return "meta_description";
  if (label.includes("title") || kind.includes("title")) return "post_title";
  if (label.includes("excerpt")) return "post_excerpt";
  return null;
}

/** The URL a fix applies to, when it applies to exactly one. */
export function urlFor(approval: ApprovalRecord): string | null {
  const target = approval.fix?.target ?? null;
  if (!target) return null;
  try {
    new URL(target);
    return target;
  } catch {
    return null;
  }
}

export type Publishable = { field: PublishField; url: string; value: string };

/** Whether this approval can be pushed live, and with what. */
export function publishable(approval: ApprovalRecord): Publishable | null {
  // Only the fix kinds that live in a post's own fields. "file", "redirect"
  // and "link_plan" are real work, but they are not a REST write.
  if (approval.fix?.kind !== "meta" && approval.fix?.kind !== "copy") return null;
  const field = fieldFor(approval);
  const url = urlFor(approval);
  const value = approval.fix?.after ?? null;
  if (!field || !url || !value) return null;
  if (approval.risk === "critical") return null;
  return { field, url, value };
}

/**
 * Queue it, approve it, publish it.
 *
 * `siteId` is the server's site id, which is not the browser's: the server
 * creates one per origin per account when a run is claimed. It is looked up
 * rather than assumed.
 */
export async function publishNow(
  approval: ApprovalRecord,
  serverSiteId: string,
  plan: Publishable,
): Promise<PublishOutcome> {
  const queued = await post<{ id: string }>("/api/approvals", {
    siteId: serverSiteId,
    runId: approval.runId,
    findingId: approval.findingId,
    kind: approval.kind,
    risk: approval.risk,
    title: approval.title,
    detail: approval.summary,
    payload: { request: { kind: plan.field, url: plan.url, value: plan.value } },
  });

  await post(`/api/approvals/${encodeURIComponent(queued.id)}`, { status: "approved" });

  const result = await post<PublishOutcome>("/api/publish", { approvalId: queued.id });
  return result;
}

export type ServerSite = { id: string; url: string; name: string };

/** The account's site whose origin matches this one, or null. */
export async function serverSiteFor(baseUrl: string): Promise<string | null> {
  try {
    const response = await fetch("/api/sites", { credentials: "same-origin" });
    if (!response.ok) return null;
    const body = (await response.json()) as { sites: ServerSite[] };
    const origin = new URL(baseUrl).origin;
    return body.sites.find((site) => site.url === origin)?.id ?? null;
  } catch {
    return null;
  }
}
