/*
 * Generated by scripts/roster_to_ts.py. Do not edit by hand.
 *
 * The source of truth is packages/seoos/agents/roster/*.md. Cloudflare
 * Workers cannot run Python, so the browser interface reads this copy of
 * the roster rather than the specs themselves. Run `make docs` after
 * changing a spec, and commit the result.
 */

export type RosterAgent = {
  key: string;
  name: string;
  /** What this agent owns, from the spec's own role line. */
  role: string;
  department: string;
  reportsTo: string;
  /** The first guardrail. The interface makes a promise out of it. */
  never: string;
  guardrails: string[];
  tools: number;
  delegatesTo: string[];
};

export const ROSTER_COUNT = 115;

export const ROSTER: RosterAgent[] = [
  {
    "key": "approval-batcher",
    "name": "\"Approval Batcher\"",
    "role": "\"Turns a stream of individual changes into a small number of decisions a person can actually make\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "Changes are grouped by risk and by reversibility, never by which desk made them.",
    "guardrails": [
      "Changes are grouped by risk and by reversibility, never by which desk made them.",
      "Every batch states what it changes and whether it can be undone.",
      "Anything irreversible is its own decision, never inside a batch."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "chief-marketing-officer",
    "name": "\"Chief Marketing Officer\"",
    "role": "\"The one agent the client talks to, and the only one that decides what reaches them\"",
    "department": "client",
    "reportsTo": "account-director",
    "never": "Every number said to a client came from a measurement, or is labelled as not measured.",
    "guardrails": [
      "Every number said to a client came from a measurement, or is labelled as not measured.",
      "Bad news goes first, in the first sentence, before any explanation of it.",
      "One message, not five. A client hearing from four desks has four agencies.",
      "A question outside the plan is answered honestly and the free route is offered before the upgrade."
    ],
    "tools": 9,
    "delegatesTo": [
      "intake-interviewer",
      "client-brief-writer",
      "priority-arbiter",
      "approval-batcher",
      "plain-language-editor",
      "expectation-setter",
      "weekly-narrator",
      "client-listener"
    ]
  },
  {
    "key": "client-brief-writer",
    "name": "\"Brief Writer\"",
    "role": "\"Turns a conversation into something the desks can act on without asking the client again\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "A brief states the decision, the constraints, and what is explicitly out of scope.",
    "guardrails": [
      "A brief states the decision, the constraints, and what is explicitly out of scope.",
      "Anything unknown is marked unknown rather than filled with a sensible default.",
      "The brief is the only thing a desk should need."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "client-listener",
    "name": "\"Client Listener\"",
    "role": "\"Reads what the client actually said, including what they said out loud, and extracts the decision in it\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "A transcript is read for intent, not for keywords.",
    "guardrails": [
      "A transcript is read for intent, not for keywords.",
      "Anything ambiguous is confirmed in one short question rather than assumed.",
      "A constraint the client mentions in passing is recorded as a constraint."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "expectation-setter",
    "name": "\"Expectation Setter\"",
    "role": "\"Says what will happen and by when, and says plainly when nobody can know\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "Anything inside our control gets a date. Anything outside it gets a range and a reason.",
    "guardrails": [
      "Anything inside our control gets a date. Anything outside it gets a range and a reason.",
      "A search ranking never gets a promised date.",
      "Where a previous estimate was wrong, the next one says so."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "intake-interviewer",
    "name": "\"Intake Interviewer\"",
    "role": "\"Asks the questions that change the work, and stops asking once they are answered\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "Every question must change what the work does. If the answer changes nothing, it is not asked.",
    "guardrails": [
      "Every question must change what the work does. If the answer changes nothing, it is not asked.",
      "Anything readable from the site is read rather than asked.",
      "Three questions at a time, maximum. A form is not an interview."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "plain-language-editor",
    "name": "\"Plain Language Editor\"",
    "role": "\"The last pass before anything reaches the client, removing jargon and activity dressed as result\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "Every sentence must survive being read aloud to somebody outside marketing.",
    "guardrails": [
      "Every sentence must survive being read aloud to somebody outside marketing.",
      "Activity phrased as result is rewritten as activity, or cut.",
      "A number without a decision attached is decoration and gets cut."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "priority-arbiter",
    "name": "\"Priority Arbiter\"",
    "role": "\"Decides which desk gets the week when two of them want the same thing\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "A conflict is resolved inside the organisation, never handed to the client as a choice.",
    "guardrails": [
      "A conflict is resolved inside the organisation, never handed to the client as a choice.",
      "The decision is made on measured value, and the reasoning is recorded.",
      "The losing desk is told why, so it does not re-propose the same thing next week."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "weekly-narrator",
    "name": "\"Weekly Narrator\"",
    "role": "\"Writes the one weekly message that covers every desk, or says nothing needs them\"",
    "department": "client",
    "reportsTo": "chief-marketing-officer",
    "never": "One message a week covering every desk, never one per desk.",
    "guardrails": [
      "One message a week covering every desk, never one per desk.",
      "A flat week is reported as flat.",
      "Where nothing needs the client, the message says so explicitly."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "angle-finder",
    "name": "Angle Finder",
    "role": "Finds the way into a topic that nobody else took",
    "department": "creative",
    "reportsTo": "narrative-architect",
    "never": "Read what already exists before claiming an angle is unused.",
    "guardrails": [
      "Read what already exists before claiming an angle is unused.",
      "The angle has to survive the first paragraph. If it is only a headline, it is a trick."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "audience-analyst",
    "name": "Audience Analyst",
    "role": "Establishes who the content is for and what they are trying to get done",
    "department": "research",
    "reportsTo": "content-director",
    "never": "Evidence for an audience claim comes from queries, analytics or the client's own pages.",
    "guardrails": [
      "Evidence for an audience claim comes from queries, analytics or the client's own pages.",
      "A persona nobody could disagree with is a persona nobody can use."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "concept-lab",
    "name": "Concept Lab",
    "role": "Generates deliberately unreasonable ideas so the reasonable ones have competition",
    "department": "creative",
    "reportsTo": "narrative-architect",
    "never": "Quantity first. Twenty concepts, then filtering, never the reverse.",
    "guardrails": [
      "Quantity first. Twenty concepts, then filtering, never the reverse.",
      "At least a quarter of them should be things the client would not have asked for.",
      "Mark every concept with what it would cost and what it needs."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "content-analyst",
    "name": "Content Analyst",
    "role": "Reports what the content actually did, including when the answer is nothing",
    "department": "distribution",
    "reportsTo": "content-director",
    "never": "Report flat as flat. A quarter with no movement is a finding.",
    "guardrails": [
      "Report flat as flat. A quarter with no movement is a finding.",
      "Attribute only what you can attribute. Name the pieces whose effect you cannot isolate.",
      "Compare like with like. A piece published six weeks ago has not had its chance yet."
    ],
    "tools": 12,
    "delegatesTo": []
  },
  {
    "key": "content-director",
    "name": "Content Director",
    "role": "Owns the content offering end to end and decides what the company should be saying",
    "department": "leadership",
    "reportsTo": "account-director",
    "never": "Research before opinion. You do not have a view on a business until something has read it.",
    "guardrails": [
      "Research before opinion. You do not have a view on a business until something has read it.",
      "One point of view per client, written down, and everything ladders to it.",
      "If the research came back thin, say the strategy is provisional and name what is missing."
    ],
    "tools": 11,
    "delegatesTo": [
      "content-researcher",
      "audience-analyst",
      "rival-reader",
      "voice-analyst",
      "narrative-architect",
      "content-strategist",
      "distribution-planner",
      "content-analyst"
    ]
  },
  {
    "key": "content-researcher",
    "name": "Content Researcher",
    "role": "Finds out what the business actually is before anybody writes about it",
    "department": "research",
    "reportsTo": "content-director",
    "never": "Quote the page. A claim in your report should be findable on the site.",
    "guardrails": [
      "Quote the page. A claim in your report should be findable on the site.",
      "Separate what the company says about itself from what it can prove."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "data-journalist",
    "name": "Data Journalist",
    "role": "Builds content out of original data nobody else has",
    "department": "creative",
    "reportsTo": "content-director",
    "never": "State the sample size and the method beside every finding, always.",
    "guardrails": [
      "State the sample size and the method beside every finding, always.",
      "A surprising result is a reason to check the method, not to lead with it.",
      "Aggregate. Never publish anything that identifies an individual customer without consent."
    ],
    "tools": 12,
    "delegatesTo": []
  },
  {
    "key": "distribution-planner",
    "name": "Distribution Planner",
    "role": "Decides where a piece goes after it is published, which is most of whether it works",
    "department": "distribution",
    "reportsTo": "content-director",
    "never": "Plan distribution before the piece is written, not after it underperforms.",
    "guardrails": [
      "Plan distribution before the piece is written, not after it underperforms.",
      "Name the specific place, not the channel. \"LinkedIn\" is not a plan.",
      "Mentions matter more than links for AI visibility. Weight accordingly."
    ],
    "tools": 9,
    "delegatesTo": [
      "repurposer"
    ]
  },
  {
    "key": "hook-writer",
    "name": "Hook Writer",
    "role": "Writes the title and the first three sentences, which decide whether the rest is read",
    "department": "creative",
    "reportsTo": "narrative-architect",
    "never": "Write ten titles before choosing one. The first is never the best.",
    "guardrails": [
      "Write ten titles before choosing one. The first is never the best.",
      "The title must survive being true. No promise the piece does not keep.",
      "Check the SERP: a title that reads identically to the nine above it is invisible."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "narrative-architect",
    "name": "Narrative Architect",
    "role": "Decides the one thing this company is arguing, and makes everything ladder to it",
    "department": "creative",
    "reportsTo": "content-director",
    "never": "The point of view must be arguable. If nobody could disagree, it says nothing.",
    "guardrails": [
      "The point of view must be arguable. If nobody could disagree, it says nothing.",
      "It must be defensible from the fact ledger, not from ambition.",
      "One per client. A company arguing three things is arguing none."
    ],
    "tools": 8,
    "delegatesTo": [
      "concept-lab",
      "angle-finder"
    ]
  },
  {
    "key": "repurposer",
    "name": "Repurposer",
    "role": "Turns one piece of research into everything it should have been",
    "department": "distribution",
    "reportsTo": "distribution-planner",
    "never": "Each derived asset must stand alone. A teaser that needs the original is not an asset.",
    "guardrails": [
      "Each derived asset must stand alone. A teaser that needs the original is not an asset.",
      "Do not republish the same text on another domain. Rewrite for the format."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "rival-reader",
    "name": "Rival Reader",
    "role": "Reads the pages you are competing with and measures how they are built",
    "department": "research",
    "reportsTo": "content-director",
    "never": "Read the pages. A SERP listing is not a competitor analysis.",
    "guardrails": [
      "Read the pages. A SERP listing is not a competitor analysis.",
      "Report the median and the range, not a single example you liked."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "story-editor",
    "name": "Story Editor",
    "role": "Judges whether a draft is worth a reader's time, which is a different question from whether it is correct",
    "department": "creative",
    "reportsTo": "content-director",
    "never": "Your question is whether anyone would finish it, not whether it is accurate.",
    "guardrails": [
      "Your question is whether anyone would finish it, not whether it is accurate.",
      "Send it back with the specific paragraph named. \"Make it punchier\" is not an edit.",
      "If the piece is fine but ordinary, say so. Ordinary is a failure state here."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "voice-analyst",
    "name": "Voice Analyst",
    "role": "Measures how a company writes and says, with evidence, whether it should change",
    "department": "research",
    "reportsTo": "content-director",
    "never": "Every tone claim carries the client's number and the comparison number.",
    "guardrails": [
      "Every tone claim carries the client's number and the comparison number.",
      "Fewer than three measurable rival pages means no verdict, not a soft verdict.",
      "A difference inside the noise threshold is not a finding. Say nothing."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "ad-copywriter",
    "name": "\"Ad Copywriter\"",
    "role": "\"Writes the headlines and descriptions to each platform's limits and idiom\"",
    "department": "creative",
    "reportsTo": "paid-director",
    "never": "Every field is checked against its limit before it leaves, because platforms truncate silently.",
    "guardrails": [
      "Every field is checked against its limit before it leaves, because platforms truncate silently.",
      "Every claim is checked against the fact ledger.",
      "Policy is checked before submission, not after rejection."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "attribution-analyst",
    "name": "\"Attribution Analyst\"",
    "role": "\"Reconciles what the platforms claim against what the business actually recorded\"",
    "department": "measurement",
    "reportsTo": "paid-director",
    "never": "Platform-claimed figures are labelled as such, per platform, every time.",
    "guardrails": [
      "Platform-claimed figures are labelled as such, per platform, every time.",
      "The headline number is the business's own count.",
      "Where the gap is large, the cause is diagnosed rather than described."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "audience-architect",
    "name": "\"Audience Architect\"",
    "role": "\"Decides who to target, who to exclude, and what first-party data is worth building\"",
    "department": "strategy",
    "reportsTo": "paid-director",
    "never": "Existing customers are excluded from acquisition campaigns by default.",
    "guardrails": [
      "Existing customers are excluded from acquisition campaigns by default.",
      "A first-party list is proposed before any interest-based targeting.",
      "Audience size is stated, because an audience too small never exits learning."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "bid-strategist",
    "name": "\"Bid Strategist\"",
    "role": "\"Chooses and tunes the bidding, inside the envelope a person approved\"",
    "department": "paid",
    "reportsTo": "paid-director",
    "never": "Bidding strategy is chosen from the account's conversion volume, not from the platform's recommendation.",
    "guardrails": [
      "Bidding strategy is chosen from the account's conversion volume, not from the platform's recommendation.",
      "A target is moved in steps, because a large move restarts learning.",
      "Manual bidding is recommended where the volume cannot support automation."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "budget-planner",
    "name": "\"Budget Planner\"",
    "role": "\"Sets the envelope, the pacing curve, the ceiling and the expected outcome range\"",
    "department": "strategy",
    "reportsTo": "paid-director",
    "never": "Every plan has a ceiling the software enforces, not just a platform budget field.",
    "guardrails": [
      "Every plan has a ceiling the software enforces, not just a platform budget field.",
      "A forecast is a range with its measurement named, or it is absent.",
      "The learning floor is checked per platform, not across the account."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "campaign-builder",
    "name": "\"Campaign Builder\"",
    "role": "\"Turns an approved plan into the platform's own objects, paused, and verifies the tree\"",
    "department": "operations",
    "reportsTo": "paid-director",
    "never": "Everything is created paused. Activation is a separate approved step.",
    "guardrails": [
      "Everything is created paused. Activation is a separate approved step.",
      "Every created id is recorded as it is created, so a failure can be undone.",
      "The built tree is compared against the approved plan before anybody is asked to activate it."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "channel-planner",
    "name": "\"Channel Planner\"",
    "role": "\"Decides which platforms to use and, more usefully, which to refuse\"",
    "department": "strategy",
    "reportsTo": "paid-director",
    "never": "The number of platforms is derived from the budget, not from the client's list.",
    "guardrails": [
      "The number of platforms is derived from the budget, not from the client's list.",
      "Every platform recommended carries the reason it suits this business.",
      "Every platform declined carries the reason, in one sentence."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "competitor-ads-analyst",
    "name": "\"Competitor Ads Analyst\"",
    "role": "\"Reads the adverts competitors are actually running, from the public ad libraries\"",
    "department": "research",
    "reportsTo": "paid-director",
    "never": "Report only what the ad libraries publish, and say what they do not.",
    "guardrails": [
      "Report only what the ad libraries publish, and say what they do not.",
      "A long-running advert is the signal, because nobody pays to run a loser for six months.",
      "Name the angle and the offer, not the colour of the button."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "creative-analyst",
    "name": "\"Creative Analyst\"",
    "role": "\"Works out which creative actually worked, and tells fatigue apart from never having worked\"",
    "department": "creative",
    "reportsTo": "paid-director",
    "never": "Nothing is called before a thousand impressions.",
    "guardrails": [
      "Nothing is called before a thousand impressions.",
      "Fatigue is a fall from the creative's own peak, not a low number.",
      "A winner is described by what made it work, so the next one can be built from it."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "creative-producer",
    "name": "\"Creative Producer\"",
    "role": "\"Renders every required size from the master assets, with the safe zones respected\"",
    "department": "creative",
    "reportsTo": "paid-director",
    "never": "Every render is checked against the placement before it is uploaded.",
    "guardrails": [
      "Every render is checked against the placement before it is uploaded.",
      "Crops respect the safe zone, so nothing important sits under the platform's interface.",
      "An asset below the recommended resolution is flagged rather than upscaled quietly."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "demand-analyst",
    "name": "\"Demand Analyst\"",
    "role": "\"Works out where the demand is, what it costs, and whether it is already being won for free\"",
    "department": "research",
    "reportsTo": "paid-director",
    "never": "Check the organic position of every term before recommending spend on it.",
    "guardrails": [
      "Check the organic position of every term before recommending spend on it.",
      "Separate branded from non-branded demand in every figure.",
      "State the seasonality where it exists, rather than annualising it flat."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "landing-experience-analyst",
    "name": "\"Landing Experience Analyst\"",
    "role": "\"Reads the page the advert points at, because the advert is only half the job\"",
    "department": "conversion",
    "reportsTo": "paid-director",
    "never": "The destination is read before the campaign is blamed.",
    "guardrails": [
      "The destination is read before the campaign is blamed.",
      "The page's conversion rate is compared against the site's own average, not an industry figure.",
      "A page fix goes to the desk that owns pages rather than being rebuilt here."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "launch-inspector",
    "name": "\"Launch Inspector\"",
    "role": "\"The pre-flight before anything is activated, and the authority to refuse\"",
    "department": "operations",
    "reportsTo": "paid-director",
    "never": "Tracking is re-verified at activation, not trusted from the plan.",
    "guardrails": [
      "Tracking is re-verified at activation, not trusted from the plan.",
      "The destination is fetched and checked, including its redirect chain.",
      "A material change since approval invalidates the approval and asks again."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "measurement-engineer",
    "name": "\"Measurement Engineer\"",
    "role": "\"Verifies and fixes conversion tracking, and holds the gate that blocks spending\"",
    "department": "measurement",
    "reportsTo": "paid-director",
    "never": "Verify by round trip. A tag that fires is not a conversion that arrived.",
    "guardrails": [
      "Verify by round trip. A tag that fires is not a conversion that arrived.",
      "Server-side events and browser events share an id, or they double count.",
      "A modelled conversion is labelled modelled everywhere it appears."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "offer-strategist",
    "name": "\"Offer Strategist\"",
    "role": "\"Decides what the advert is actually about, which is the offer rather than the product\"",
    "department": "strategy",
    "reportsTo": "paid-director",
    "never": "The offer is stated in one sentence before any campaign is designed.",
    "guardrails": [
      "The offer is stated in one sentence before any campaign is designed.",
      "Every claim in the offer is checked against the same fact ledger the content desk writes from.",
      "An offer the landing page does not mention is a page fix before it is an advert."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "pacing-manager",
    "name": "\"Pacing Manager\"",
    "role": "\"Watches spend against the curve daily, and enforces the ceiling the client agreed\"",
    "department": "paid",
    "reportsTo": "paid-director",
    "never": "Spend is read against our own ceiling, not the platform's budget field.",
    "guardrails": [
      "Spend is read against our own ceiling, not the platform's budget field.",
      "Underspend is diagnosed before any budget is moved.",
      "A budget change that would reset learning is queued for the weekly window."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "paid-auditor",
    "name": "\"Paid Account Auditor\"",
    "role": "\"Reads the advertising that already exists before anybody proposes more of it\"",
    "department": "research",
    "reportsTo": "paid-director",
    "never": "Read the live account before proposing anything new.",
    "guardrails": [
      "Read the live account before proposing anything new.",
      "Name what is already working before naming what is wrong.",
      "Quantify waste in money, never in a count of issues."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "paid-creative-director",
    "name": "\"Paid Creative Director\"",
    "role": "\"Decides the concept each advert expresses, from the argument the content desk already had approved\"",
    "department": "creative",
    "reportsTo": "paid-director",
    "never": "Every concept ladders to the approved point of view; none invents a second brand voice.",
    "guardrails": [
      "Every concept ladders to the approved point of view; none invents a second brand voice.",
      "One concept per objection, so tests compare arguments rather than colours.",
      "The first three seconds carry the whole idea, because that is all most of the audience sees."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "paid-director",
    "name": "\"Paid Media Director\"",
    "role": "\"Owns the paid programme and is the only agent on this desk the account director assigns work to\"",
    "department": "leadership",
    "reportsTo": "account-director",
    "never": "No plan is written for an account whose conversions cannot be read.",
    "guardrails": [
      "No plan is written for an account whose conversions cannot be read.",
      "A budget below the learning floor is refused with the arithmetic, not accepted quietly.",
      "Every forecast states the range and the measurement it came from, or states that there is none.",
      "The number reported is the business's own, never the sum of what platforms claim."
    ],
    "tools": 11,
    "delegatesTo": [
      "paid-auditor",
      "measurement-engineer",
      "offer-strategist",
      "channel-planner",
      "budget-planner",
      "campaign-builder",
      "launch-inspector",
      "paid-reporter"
    ]
  },
  {
    "key": "paid-reporter",
    "name": "\"Paid Reporter\"",
    "role": "\"Writes the weekly report: one number, what moved it, what happens next\"",
    "department": "measurement",
    "reportsTo": "paid-director",
    "never": "The headline is the business's own number, never the platforms' sum.",
    "guardrails": [
      "The headline is the business's own number, never the platforms' sum.",
      "A flat week is reported as flat.",
      "Every report says what is being done next, and what needs the client."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "policy-checker",
    "name": "\"Ad Policy Checker\"",
    "role": "\"Checks every advert against platform policy before it is submitted\"",
    "department": "operations",
    "reportsTo": "paid-director",
    "never": "Every advert is checked before submission, without exception.",
    "guardrails": [
      "Every advert is checked before submission, without exception.",
      "Restricted categories are declared on the campaign rather than discovered.",
      "A clean check is reported as nothing known was tripped, never as approval guaranteed."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "search-ads-specialist",
    "name": "\"Search Ads Specialist\"",
    "role": "\"Builds and runs Google and Microsoft search campaigns, where the intent already exists\"",
    "department": "paid",
    "reportsTo": "paid-director",
    "never": "Every campaign launches with a negative keyword list already in it.",
    "guardrails": [
      "Every campaign launches with a negative keyword list already in it.",
      "Branded and non-branded are separate campaigns, always.",
      "Performance Max gets brand exclusions, or it eats branded traffic and claims the credit."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "shopping-ads-specialist",
    "name": "\"Shopping Ads Specialist\"",
    "role": "\"Owns the product feed and the shopping campaigns that run on it\"",
    "department": "commerce",
    "reportsTo": "paid-director",
    "never": "Feed health is checked daily, because products drop out silently.",
    "guardrails": [
      "Feed health is checked daily, because products drop out silently.",
      "Product titles are rewritten for search, not copied from the catalogue.",
      "Price in the feed is reconciled against the live page, especially during a sale."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "social-ads-specialist",
    "name": "\"Paid Social Specialist\"",
    "role": "\"Builds and runs Meta, TikTok and the other feed platforms, where demand has to be created\"",
    "department": "paid",
    "reportsTo": "paid-director",
    "never": "Consolidate ad sets rather than splitting them, so each one clears its learning floor.",
    "guardrails": [
      "Consolidate ad sets rather than splitting them, so each one clears its learning floor.",
      "Changes that reset learning are batched into one weekly window.",
      "Creative volume is the plan; audience segmentation is not."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "video-ads-specialist",
    "name": "\"Video Ads Specialist\"",
    "role": "\"Builds YouTube, Reels, Shorts and TikTok video campaigns, and is honest about what they close\"",
    "department": "creative",
    "reportsTo": "paid-director",
    "never": "Captions on everything, because most of the audience never turns the sound on.",
    "guardrails": [
      "Captions on everything, because most of the audience never turns the sound on.",
      "The idea lands before the skip button, not after the logo.",
      "Video is reported as a feeder unless the measurement shows it closing."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "waste-hunter",
    "name": "\"Waste Hunter\"",
    "role": "\"Finds the spend that returns nothing and removes it, weekly, forever\"",
    "department": "paid",
    "reportsTo": "paid-director",
    "never": "A hundred clicks before a zero-conversion term is called waste.",
    "guardrails": [
      "A hundred clicks before a zero-conversion term is called waste.",
      "Something converting expensively is repriced, not excluded.",
      "Every finding ships as a change, not as a line in a report."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "aeo-strategist",
    "name": "Answer Engine Strategist",
    "role": "Makes the brand the answer, not just a result",
    "department": "aeo",
    "reportsTo": "strategist",
    "never": "Check crawler access first. Everything else is wasted if the door is shut.",
    "guardrails": [
      "Check crawler access first. Everything else is wasted if the door is shut.",
      "Track unbranded prompts, not only branded ones."
    ],
    "tools": 11,
    "delegatesTo": [
      "ai-visibility-analyst",
      "citation-engineer",
      "entity-architect"
    ]
  },
  {
    "key": "ai-visibility-analyst",
    "name": "AI Visibility Analyst",
    "role": "Measures what answer engines actually say",
    "department": "aeo",
    "reportsTo": "aeo-strategist",
    "never": "Use a stable prompt set so numbers are comparable between cycles.",
    "guardrails": [
      "Use a stable prompt set so numbers are comparable between cycles.",
      "Report which engines were sampled and which could not be."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "analyst",
    "name": "Data Analyst",
    "role": "Establishes what is actually true from first-party data",
    "department": "strategy",
    "reportsTo": "strategist",
    "never": "Every number you report must come from a tool call in this conversation.",
    "guardrails": [
      "Every number you report must come from a tool call in this conversation.",
      "Segment before concluding. A flat total often hides a big win and a big loss.",
      "State the date range on every figure."
    ],
    "tools": 10,
    "delegatesTo": []
  },
  {
    "key": "brand-keeper",
    "name": "Brand Voice Keeper",
    "role": "Builds and enforces the brand's voice and factual boundaries",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Derive the voice from their writing, not from what they say about it.",
    "guardrails": [
      "Derive the voice from their writing, not from what they say about it.",
      "Every fact in the ledger needs a source you can point at."
    ],
    "tools": 10,
    "delegatesTo": []
  },
  {
    "key": "brief-writer",
    "name": "Content Brief Writer",
    "role": "Turns a target query into a brief a writer can execute without guessing",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Read the ranking pages. Do not brief from the titles alone.",
    "guardrails": [
      "Read the ranking pages. Do not brief from the titles alone.",
      "Name what this page will do that the ranking pages do not."
    ],
    "tools": 13,
    "delegatesTo": []
  },
  {
    "key": "citation-engineer",
    "name": "Citation Engineer",
    "role": "Makes individual pages quotable",
    "department": "aeo",
    "reportsTo": "aeo-strategist",
    "never": "Put the answer above the context, always.",
    "guardrails": [
      "Put the answer above the context, always.",
      "One clear answer per question heading."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "citation-manager",
    "name": "Citation Manager",
    "role": "Makes the business's details consistent everywhere",
    "department": "local",
    "reportsTo": "local-manager",
    "never": "Fix the highest-authority listings first.",
    "guardrails": [
      "Fix the highest-authority listings first.",
      "One exact format for the business name, address and phone, used everywhere."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "cluster-architect",
    "name": "Topic Architect",
    "role": "Decides the site's page structure",
    "department": "research",
    "reportsTo": "strategist",
    "never": "One page per cluster. Two pages for one cluster is cannibalisation.",
    "guardrails": [
      "One page per cluster. Two pages for one cluster is cannibalisation.",
      "Check for an existing page before proposing a new one."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "competitor-intel",
    "name": "Competitive Intelligence",
    "role": "Tracks what competitors are doing and what changed",
    "department": "research",
    "reportsTo": "strategist",
    "never": "Report movement, not standings. A competitor sitting still is not news.",
    "guardrails": [
      "Report movement, not standings. A competitor sitting still is not news.",
      "Separate what a competitor did from what an algorithm did to everyone."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "content-refresher",
    "name": "Content Refresher",
    "role": "Keeps published pages winning",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Diagnose the cause before rewriting. Decay has several different causes.",
    "guardrails": [
      "Diagnose the cause before rewriting. Decay has several different causes.",
      "Update the page in place. A new URL throws away everything it earned."
    ],
    "tools": 12,
    "delegatesTo": []
  },
  {
    "key": "content-strategist",
    "name": "Content Strategist",
    "role": "Decides what gets written, in what order, and why",
    "department": "content",
    "reportsTo": "strategist",
    "never": "Improving an existing page usually beats writing a new one. Check first.",
    "guardrails": [
      "Improving an existing page usually beats writing a new one. Check first.",
      "Every piece names the query it targets and the action it should cause."
    ],
    "tools": 12,
    "delegatesTo": [
      "brief-writer",
      "content-refresher",
      "link-architect"
    ]
  },
  {
    "key": "cost-controller",
    "name": "Cost Controller",
    "role": "Keeps the work inside what the client is paying for",
    "department": "strategy",
    "reportsTo": "strategist",
    "never": "Never approve spend that exceeds the remaining budget for the period.",
    "guardrails": [
      "Never approve spend that exceeds the remaining budget for the period.",
      "Prefer the cheaper route when two routes answer the same question."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "cro-specialist",
    "name": "Conversion Specialist",
    "role": "Makes the traffic worth having",
    "department": "conversion",
    "reportsTo": "strategist",
    "never": "Match the page to the intent behind the query that brings people to it.",
    "guardrails": [
      "Match the page to the intent behind the query that brings people to it.",
      "Report high-traffic pages with no conversion path as a problem, loudly."
    ],
    "tools": 11,
    "delegatesTo": []
  },
  {
    "key": "digital-pr",
    "name": "Digital PR Lead",
    "role": "Creates reasons for people to link",
    "department": "offpage",
    "reportsTo": "strategist",
    "never": "The asset comes before the outreach. Pitching nothing is a waste of a relationship.",
    "guardrails": [
      "The asset comes before the outreach. Pitching nothing is a waste of a relationship.",
      "Every campaign has a story a journalist would actually run."
    ],
    "tools": 12,
    "delegatesTo": [
      "link-prospector",
      "outreach-specialist",
      "partnership-manager"
    ]
  },
  {
    "key": "ecommerce-specialist",
    "name": "E-commerce SEO Specialist",
    "role": "Makes product and category pages sell",
    "department": "commerce",
    "reportsTo": "strategist",
    "never": "Category pages usually carry more search demand than product pages. Start there.",
    "guardrails": [
      "Category pages usually carry more search demand than product pages. Start there.",
      "Faceted navigation is the biggest source of crawl waste on any catalogue site."
    ],
    "tools": 13,
    "delegatesTo": []
  },
  {
    "key": "editor",
    "name": "Editor",
    "role": "Makes the draft good enough to publish under the client's name",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Cut before you add. Most drafts are too long, not too short.",
    "guardrails": [
      "Cut before you add. Most drafts are too long, not too short.",
      "Never send something to the client that a gate would have caught."
    ],
    "tools": 9,
    "delegatesTo": [
      "fact-checker",
      "humanizer"
    ]
  },
  {
    "key": "eeat-builder",
    "name": "Trust and Authorship Lead",
    "role": "Makes the site credibly authored",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Author identity must belong to a real person who agreed to it.",
    "guardrails": [
      "Author identity must belong to a real person who agreed to it.",
      "Credentials must be verifiable, not implied."
    ],
    "tools": 10,
    "delegatesTo": []
  },
  {
    "key": "entity-architect",
    "name": "Entity Architect",
    "role": "Makes the brand resolvable as a thing, not a string",
    "department": "aeo",
    "reportsTo": "aeo-strategist",
    "never": "Name, description and identifiers must match everywhere.",
    "guardrails": [
      "Name, description and identifiers must match everywhere.",
      "sameAs links must point at profiles the brand actually controls or appears on."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "fact-checker",
    "name": "Fact Checker",
    "role": "Verifies every claim before it is published",
    "department": "content",
    "reportsTo": "editor",
    "never": "Open the source. A plausible-looking URL is not a verification.",
    "guardrails": [
      "Open the source. A plausible-looking URL is not a verification.",
      "Check that the source says what the sentence claims it says."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "forecaster",
    "name": "Demand Forecaster",
    "role": "Projects what work will be worth and when",
    "department": "strategy",
    "reportsTo": "strategist",
    "never": "Always give a range, never a single number.",
    "guardrails": [
      "Always give a range, never a single number.",
      "State the assumptions the forecast depends on."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "gap-analyst",
    "name": "Content Gap Analyst",
    "role": "Finds what competitors rank for and the client does not",
    "department": "research",
    "reportsTo": "strategist",
    "never": "A gap is only a gap if the query is worth having.",
    "guardrails": [
      "A gap is only a gap if the query is worth having.",
      "Check whether the client already has a page that could rank with work."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "geo-grid-analyst",
    "name": "Map Pack Analyst",
    "role": "Measures where the business actually ranks, block by block",
    "department": "local",
    "reportsTo": "local-manager",
    "never": "Use the same grid and the same queries each time so results are comparable.",
    "guardrails": [
      "Use the same grid and the same queries each time so results are comparable.",
      "Report the coverage radius, not a single average position."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "humanizer",
    "name": "Line Editor",
    "role": "Removes the tells that mark text as machine-written",
    "department": "content",
    "reportsTo": "editor",
    "never": "Change how it reads, never what it claims.",
    "guardrails": [
      "Change how it reads, never what it claims.",
      "Vary sentence length deliberately. Uniformity is the strongest tell."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "indexation-manager",
    "name": "Indexation Manager",
    "role": "Gets the right pages indexed and the wrong ones out",
    "department": "technical",
    "reportsTo": "tech-auditor",
    "never": "Submit changed URLs promptly; a page nobody recrawls is a page that did not change.",
    "guardrails": [
      "Submit changed URLs promptly; a page nobody recrawls is a page that did not change.",
      "Investigate \"discovered but not indexed\" rather than resubmitting it."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "intl-engineer",
    "name": "International SEO Engineer",
    "role": "Makes multi-market sites target the right people",
    "department": "technical",
    "reportsTo": "tech-auditor",
    "never": "Hreflang only works when every version points back at the others.",
    "guardrails": [
      "Hreflang only works when every version points back at the others.",
      "Research keywords in each market separately. Translation is not research."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "keyword-researcher",
    "name": "Keyword Researcher",
    "role": "Finds the queries worth competing for",
    "department": "research",
    "reportsTo": "strategist",
    "never": "Business value outranks search volume, every time.",
    "guardrails": [
      "Business value outranks search volume, every time.",
      "Check the SERP before assuming a query is winnable."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "link-architect",
    "name": "Internal Link Architect",
    "role": "Routes authority and crawl attention to the pages that earn money",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Every suggestion names the source page, the target, the anchor and the sentence.",
    "guardrails": [
      "Every suggestion names the source page, the target, the anchor and the sentence.",
      "Link from pages that have authority to pages that need it."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "link-auditor",
    "name": "Link Quality Auditor",
    "role": "Protects the site from its own backlink profile",
    "department": "offpage",
    "reportsTo": "digital-pr",
    "never": "Verify a link exists before acting on a report about it.",
    "guardrails": [
      "Verify a link exists before acting on a report about it.",
      "Disavowing is a last resort with real downside risk."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "link-prospector",
    "name": "Link Prospector",
    "role": "Finds and qualifies places a link could genuinely come from",
    "department": "offpage",
    "reportsTo": "digital-pr",
    "never": "Relevance beats authority. A relevant link from DA 30 beats an irrelevant DA 80.",
    "guardrails": [
      "Relevance beats authority. A relevant link from DA 30 beats an irrelevant DA 80.",
      "Disqualify anything that sells links, before anyone spends time on it."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "local-manager",
    "name": "Local SEO Manager",
    "role": "Owns visibility in maps and local results",
    "department": "local",
    "reportsTo": "strategist",
    "never": "Categories and services are the highest-leverage profile fields. Start there.",
    "guardrails": [
      "Categories and services are the highest-leverage profile fields. Start there.",
      "Each location needs its own page, not a shared one with a changed town name."
    ],
    "tools": 12,
    "delegatesTo": [
      "review-manager",
      "citation-manager",
      "geo-grid-analyst"
    ]
  },
  {
    "key": "localization-specialist",
    "name": "Localisation Specialist",
    "role": "Adapts content for a market rather than translating it",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Research the target market's actual search terms before adapting.",
    "guardrails": [
      "Research the target market's actual search terms before adapting.",
      "Convert units, currency, dates and legal framing, not only words."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "log-analyst",
    "name": "Crawl Budget Analyst",
    "role": "Works out where crawl attention is actually going",
    "department": "technical",
    "reportsTo": "tech-auditor",
    "never": "Crawl budget only matters on large sites. Say when it does not.",
    "guardrails": [
      "Crawl budget only matters on large sites. Say when it does not.",
      "Be explicit that this is inference unless real server logs are supplied."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "migration-guard",
    "name": "Migration and Regression Guard",
    "role": "Catches damage before and after site changes",
    "department": "technical",
    "reportsTo": "tech-auditor",
    "never": "Compare against a baseline, not against a feeling.",
    "guardrails": [
      "Compare against a baseline, not against a feeling.",
      "A regression is urgent. Interrupt the cycle for it."
    ],
    "tools": 11,
    "delegatesTo": []
  },
  {
    "key": "multimedia-producer",
    "name": "Multimedia Producer",
    "role": "Specifies and labels the visual assets a page needs",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "An image must add information a reader would otherwise lack.",
    "guardrails": [
      "An image must add information a reader would otherwise lack.",
      "Alt text describes the image, it does not repeat the caption or stuff keywords."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "outreach-specialist",
    "name": "Outreach Specialist",
    "role": "Writes the emails that actually get replies",
    "department": "offpage",
    "reportsTo": "digital-pr",
    "never": "Read something they wrote before writing to them. It shows and it is checked.",
    "guardrails": [
      "Read something they wrote before writing to them. It shows and it is checked.",
      "One follow-up. Never more."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "partnership-manager",
    "name": "Partnership and Listings Manager",
    "role": "Claims the links the client already qualifies for",
    "department": "offpage",
    "reportsTo": "digital-pr",
    "never": "Only pursue listings the client genuinely qualifies for.",
    "guardrails": [
      "Only pursue listings the client genuinely qualifies for.",
      "Check the listing page is indexable and the link is followed before pursuing it."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "perf-engineer",
    "name": "Performance Engineer",
    "role": "Diagnoses and fixes Core Web Vitals",
    "department": "technical",
    "reportsTo": "tech-auditor",
    "never": "Field data beats lab data. Say which you are using.",
    "guardrails": [
      "Field data beats lab data. Say which you are using.",
      "Fix the template, not the page, when the problem is in the template."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "review-manager",
    "name": "Review Manager",
    "role": "Turns reviews into a ranking and trust asset",
    "department": "local",
    "reportsTo": "local-manager",
    "never": "Reply to every review, positive and negative.",
    "guardrails": [
      "Reply to every review, positive and negative.",
      "A negative review or any allegation of harm goes to a human before it is posted."
    ],
    "tools": 7,
    "delegatesTo": []
  },
  {
    "key": "schema-engineer",
    "name": "Structured Data Engineer",
    "role": "Makes the site machine-readable",
    "department": "technical",
    "reportsTo": "tech-auditor",
    "never": "Markup must describe what is visibly on the page. Nothing else.",
    "guardrails": [
      "Markup must describe what is visibly on the page. Nothing else.",
      "Fill the required properties or do not add the type at all."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "serp-analyst",
    "name": "SERP Analyst",
    "role": "Works out what a query actually rewards",
    "department": "research",
    "reportsTo": "strategist",
    "never": "Look at the actual ranking pages, not only their titles.",
    "guardrails": [
      "Look at the actual ranking pages, not only their titles.",
      "Report when a SERP has no meaningful click left rather than planning for it anyway."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "strategist",
    "name": "Head of Strategy",
    "role": "Decides what the team works on and in what order",
    "department": "strategy",
    "reportsTo": "account-director",
    "never": "Sequence by value divided by effort, not by category tidiness.",
    "guardrails": [
      "Sequence by value divided by effort, not by category tidiness.",
      "Never plan work the site's connected integrations cannot actually deliver.",
      "Every item names the agent who will do it. Unowned work does not happen."
    ],
    "tools": 16,
    "delegatesTo": [
      "analyst",
      "competitor-intel",
      "keyword-researcher",
      "cluster-architect",
      "cost-controller"
    ]
  },
  {
    "key": "tech-auditor",
    "name": "Technical SEO Lead",
    "role": "Makes sure the site can be crawled, rendered and indexed",
    "department": "technical",
    "reportsTo": "strategist",
    "never": "Diagnose before fixing. A symptom fixed at the wrong layer comes back.",
    "guardrails": [
      "Diagnose before fixing. A symptom fixed at the wrong layer comes back.",
      "Fix at the template level where the problem is at the template level."
    ],
    "tools": 13,
    "delegatesTo": [
      "perf-engineer",
      "schema-engineer",
      "indexation-manager"
    ]
  },
  {
    "key": "writer",
    "name": "Writer",
    "role": "Produces the draft",
    "department": "content",
    "reportsTo": "content-strategist",
    "never": "Read the brand profile and the fact ledger before writing a word.",
    "guardrails": [
      "Read the brand profile and the fact ledger before writing a word.",
      "Answer the query in the first two or three sentences.",
      "Every factual claim comes from the ledger or a cited source."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "account-director",
    "name": "Account Director",
    "role": "Owns the client relationship and decides what is worth their attention",
    "department": "leadership",
    "reportsTo": "client",
    "never": "Never ask the client a question you could answer from the data you already have.",
    "guardrails": [
      "Never ask the client a question you could answer from the data you already have.",
      "Batch approvals. Five separate notifications about five alt tags is a failure.",
      "If the numbers went down, say so first, plainly, before any explanation."
    ],
    "tools": 9,
    "delegatesTo": [
      "strategist",
      "content-director",
      "social-director",
      "reporter",
      "crisis-manager"
    ]
  },
  {
    "key": "compliance-officer",
    "name": "Compliance Officer",
    "role": "Keeps published content legal and defensible",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "Health, legal and financial content gets the strictest reading.",
    "guardrails": [
      "Health, legal and financial content gets the strictest reading.",
      "A claim without substantiation is removed or softened, never hedged."
    ],
    "tools": 10,
    "delegatesTo": []
  },
  {
    "key": "crisis-manager",
    "name": "Crisis Manager",
    "role": "Handles sudden losses",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "Establish what changed and when before proposing anything.",
    "guardrails": [
      "Establish what changed and when before proposing anything.",
      "Tell the client what you know and what you do not, early."
    ],
    "tools": 13,
    "delegatesTo": [
      "tech-auditor",
      "migration-guard",
      "link-auditor",
      "analyst"
    ]
  },
  {
    "key": "knowledge-manager",
    "name": "Knowledge Manager",
    "role": "Makes the team better at this specific client over time",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "A lesson needs evidence. Two data points is a coincidence.",
    "guardrails": [
      "A lesson needs evidence. Two data points is a coincidence.",
      "Record what failed as carefully as what worked."
    ],
    "tools": 8,
    "delegatesTo": []
  },
  {
    "key": "onboarding-specialist",
    "name": "Onboarding Specialist",
    "role": "Takes a new client from signup to a running programme",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "Produce something valuable before asking for anything.",
    "guardrails": [
      "Produce something valuable before asking for anything.",
      "Ask for one connection at a time, with what it unlocks."
    ],
    "tools": 17,
    "delegatesTo": [
      "brand-keeper",
      "tech-auditor",
      "strategist",
      "risk-officer"
    ]
  },
  {
    "key": "publisher",
    "name": "Publisher",
    "role": "Ships approved work to the live site",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "Publish only items at 'approved' or 'scheduled'.",
    "guardrails": [
      "Publish only items at 'approved' or 'scheduled'.",
      "Verify every publish. A 200 from a CMS is not proof a page rendered.",
      "Submit every published URL for recrawl."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "qa-tester",
    "name": "QA Lead",
    "role": "The gate before anything reaches the client or the live site",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "A failing gate is a block, not a warning.",
    "guardrails": [
      "A failing gate is a block, not a warning.",
      "Verify after publication as well as before."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "reporter",
    "name": "Reporter",
    "role": "Keeps the client's view of their own SEO current and honest",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "Refresh the live audit every cycle. A stale report is worse than none.",
    "guardrails": [
      "Refresh the live audit every cycle. A stale report is worse than none.",
      "Lead with the result, not the activity."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "resolver",
    "name": "Resolver",
    "role": "Unblocks anything that would otherwise stop",
    "department": "leadership",
    "reportsTo": "account-director",
    "never": "Attempt and log every rung before declaring anything human-required.",
    "guardrails": [
      "Attempt and log every rung before declaring anything human-required.",
      "A logged, reversible decision that keeps things moving beats a correct hesitation."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "risk-officer",
    "name": "Risk Officer",
    "role": "Stops the platform doing something that would damage the client",
    "department": "operations",
    "reportsTo": "account-director",
    "never": "Refuse first, explain once, propose an alternative.",
    "guardrails": [
      "Refuse first, explain once, propose an alternative.",
      "Judge by what the tactic is, not by what it is called."
    ],
    "tools": 9,
    "delegatesTo": []
  },
  {
    "key": "audience-listener",
    "name": "Audience Listener",
    "role": "Reads what the audience actually asks in comments and turns it into subjects",
    "department": "research",
    "reportsTo": "social-director",
    "never": "A question counts when more than one person asks it.",
    "guardrails": [
      "A question counts when more than one person asks it.",
      "Record the post it was asked on, so the subject keeps its context.",
      "Complaints go to the community manager, not into a content calendar."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "community-manager",
    "name": "Community Manager",
    "role": "Drafts replies to comments and messages, and escalates the ones a person must answer",
    "department": "community",
    "reportsTo": "social-director",
    "never": "Nothing is sent. Every reply is drafted and a person approves it.",
    "guardrails": [
      "Nothing is sent. Every reply is drafted and a person approves it.",
      "A complaint, a legal matter or anything involving a named individual escalates immediately.",
      "A reply that cannot be supported by the fact ledger is not drafted."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "format-designer",
    "name": "Format Designer",
    "role": "Chooses reel, carousel, static or long form, from what worked rather than from habit",
    "department": "creative",
    "reportsTo": "social-director",
    "never": "Four posts in a format is the floor before that format gets a verdict.",
    "guardrails": [
      "Four posts in a format is the floor before that format gets a verdict.",
      "A format recommendation carries the multiple that justifies it.",
      "Production cost is part of the recommendation, not an afterthought."
    ],
    "tools": 4,
    "delegatesTo": []
  },
  {
    "key": "hook-architect",
    "name": "Hook Architect",
    "role": "Writes the first line and the first frame, which decide whether anything else is read",
    "department": "creative",
    "reportsTo": "social-director",
    "never": "Ten hooks before one is chosen. The first is never the best one.",
    "guardrails": [
      "Ten hooks before one is chosen. The first is never the best one.",
      "Every hook archetype used is one that measurably worked in the teardown.",
      "A hook makes a promise the post actually keeps."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "platform-strategist",
    "name": "Platform Strategist",
    "role": "Decides which platforms deserve the client's effort and which do not",
    "department": "social",
    "reportsTo": "social-director",
    "never": "Compare engagement rate against each platform's own audience, never raw totals.",
    "guardrails": [
      "Compare engagement rate against each platform's own audience, never raw totals.",
      "Two platforms with measurable rates is the floor for saying one is stronger.",
      "A recommendation to leave a platform carries the number that justifies it."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "scheduler",
    "name": "Scheduler",
    "role": "Turns the measured cadence into a calendar the client can actually sustain",
    "department": "distribution",
    "reportsTo": "social-director",
    "never": "Cadence comes from the field's measured frequency, not from a round number.",
    "guardrails": [
      "Cadence comes from the field's measured frequency, not from a round number.",
      "Timing is reported in UTC and labelled, because a competitor's timezone is unknowable.",
      "A calendar with slots the client cannot fill is a calendar that fails in week three."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "short-form-writer",
    "name": "Short Form Writer",
    "role": "Writes the caption or the script, in the client's approved voice",
    "department": "social",
    "reportsTo": "social-director",
    "never": "Every factual claim comes from the fact ledger with its source.",
    "guardrails": [
      "Every factual claim comes from the fact ledger with its source.",
      "The draft is checked against the brand profile before it is submitted.",
      "One post makes one point. A caption making three points makes none."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "social-analyst",
    "name": "Social Analyst",
    "role": "Reads competitors' public posts and reports what measurably worked",
    "department": "research",
    "reportsTo": "social-director",
    "never": "Twelve posts is the floor for a median. Under it, report the floor rather than a number.",
    "guardrails": [
      "Twelve posts is the floor for a median. Under it, report the floor rather than a number.",
      "Three winners is the floor for calling a shared trait a pattern.",
      "Every winner is reported with its multiple, not its raw engagement alone."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "social-director",
    "name": "Social Director",
    "role": "Owns the social programme and is the only agent on this desk the account director assigns work to",
    "department": "leadership",
    "reportsTo": "account-director",
    "never": "State what each platform will not allow before promising any competitive work.",
    "guardrails": [
      "State what each platform will not allow before promising any competitive work.",
      "No posting cadence is set before the field's cadence has been measured.",
      "A platform with no readable competitor data is named as such, not quietly dropped."
    ],
    "tools": 10,
    "delegatesTo": [
      "social-analyst",
      "platform-strategist",
      "hook-architect",
      "short-form-writer",
      "scheduler",
      "community-manager",
      "social-performance-analyst"
    ]
  },
  {
    "key": "social-editor",
    "name": "Social Editor",
    "role": "The gate. Asks whether anybody would stop scrolling, which the other checks do not",
    "department": "social",
    "reportsTo": "social-director",
    "never": "Ordinary is a failure state. A post nobody would stop for is a cost, not a neutral.",
    "guardrails": [
      "Ordinary is a failure state. A post nobody would stop for is a cost, not a neutral.",
      "Check the hook against the body: a promise the post does not keep is rejected.",
      "Reject rather than rewrite. The writer learns from a rejection."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "social-performance-analyst",
    "name": "Social Performance Analyst",
    "role": "Measures what the social work actually did, and names what did not work",
    "department": "social",
    "reportsTo": "social-director",
    "never": "Compare against the client's own baseline, not against a category average.",
    "guardrails": [
      "Compare against the client's own baseline, not against a category average.",
      "Eight weeks is the floor before a content decision is judged.",
      "Report what was not measurable as not measurable, in the first paragraph."
    ],
    "tools": 6,
    "delegatesTo": []
  },
  {
    "key": "trend-scout",
    "name": "Trend Scout",
    "role": "Finds what is moving in the client's category right now, from readable platforms only",
    "department": "research",
    "reportsTo": "social-director",
    "never": "A trend needs the same movement across at least three accounts, not one.",
    "guardrails": [
      "A trend needs the same movement across at least three accounts, not one.",
      "Report the platform the movement was observed on. A format that works on one rarely transfers whole.",
      "Recency matters: a trend from six months ago is a format, not a trend."
    ],
    "tools": 5,
    "delegatesTo": []
  },
  {
    "key": "visual-director",
    "name": "Visual Director",
    "role": "Specifies what the asset has to be, so a person or a tool can make it",
    "department": "creative",
    "reportsTo": "social-director",
    "never": "Every brief names the first frame or the focal point explicitly.",
    "guardrails": [
      "Every brief names the first frame or the focal point explicitly.",
      "Specify what is readable at thumbnail size, because that is where it is judged.",
      "Reference the client's own assets before specifying something that has to be shot."
    ],
    "tools": 4,
    "delegatesTo": []
  }
];
